"use client";

import {useCallback,useEffect,useRef,useState} from "react";
import ClassicFrame from "../classics/ClassicFrame";
import classic from "../classics/classic.module.css";
import {useGameAudio} from "../../useGameAudio";

type Platform={x:number;y:number;w:number;h:number};type Hazard={x:number;y:number;min:number;max:number;dir:number};type Phase="ready"|"playing"|"won"|"over";
const WORLD=2800,GROUND=470;
const PLATFORMS:Platform[]=[{x:0,y:GROUND,w:430,h:70},{x:510,y:440,w:220,h:100},{x:790,y:480,w:300,h:60},{x:1140,y:420,w:180,h:120},{x:1380,y:470,w:360,h:70},{x:1810,y:430,w:210,h:110},{x:2090,y:480,w:280,h:60},{x:2420,y:440,w:380,h:100},{x:270,y:350,w:110,h:18},{x:640,y:315,w:105,h:18},{x:930,y:365,w:120,h:18},{x:1460,y:335,w:120,h:18},{x:1650,y:300,w:100,h:18},{x:1960,y:325,w:120,h:18},{x:2250,y:345,w:105,h:18}];
const PARCELS=[{x:320,y:315},{x:680,y:280},{x:980,y:330},{x:1195,y:380},{x:1515,y:300},{x:1695,y:265},{x:2015,y:290},{x:2295,y:310},{x:2570,y:400}];
type Checkpoint={x:number;y:number};
type WorldState={x:number;y:number;vx:number;vy:number;grounded:boolean;camera:number;hearts:number;parcels:Set<number>;checkpoint:Checkpoint;hazards:Hazard[];invincible:number};
const fresh=():WorldState=>({x:70,y:GROUND-40,vx:0,vy:0,grounded:true,camera:0,hearts:3,parcels:new Set(),checkpoint:{x:70,y:GROUND-40},hazards:[{x:880,y:451,min:820,max:1040,dir:1},{x:1440,y:441,min:1410,max:1680,dir:1},{x:1870,y:401,min:1830,max:1970,dir:-1},{x:2480,y:411,min:2450,max:2660,dir:1}],invincible:0});

export default function StarCourier(){
  const audio=useGameAudio();const canvas=useRef<HTMLCanvasElement>(null);const world=useRef<WorldState>(fresh());const keys=useRef({left:false,right:false,jump:false});const phaseRef=useRef<Phase>("ready");const [phase,setPhase]=useState<Phase>("ready");const [score,setScore]=useState(0);const [best,setBest]=useState(0);const [parcels,setParcels]=useState(0);const [hearts,setHearts]=useState(3);const [distance,setDistance]=useState(0);
  const setGamePhase=(p:Phase)=>{phaseRef.current=p;setPhase(p)};useEffect(()=>{const timer=window.setTimeout(()=>{try{setBest(Number(localStorage.getItem("fairbyte:star-courier:best")||0))}catch{}},0);return()=>window.clearTimeout(timer)},[]);
  const restart=useCallback(()=>{audio.play("navigate");world.current=fresh();setScore(0);setParcels(0);setHearts(3);setDistance(0);setGamePhase("playing")},[audio]);
  useEffect(()=>{const down=(e:KeyboardEvent)=>{if(["ArrowLeft","ArrowRight","ArrowUp","a","d","w"," "].includes(e.key))e.preventDefault();if(e.key==="ArrowLeft"||e.key.toLowerCase()==="a")keys.current.left=true;if(e.key==="ArrowRight"||e.key.toLowerCase()==="d")keys.current.right=true;if(e.key==="ArrowUp"||e.key.toLowerCase()==="w"||e.key===" ")keys.current.jump=true;if(e.key==="Enter"&&phaseRef.current!=="playing")restart()};const up=(e:KeyboardEvent)=>{if(e.key==="ArrowLeft"||e.key.toLowerCase()==="a")keys.current.left=false;if(e.key==="ArrowRight"||e.key.toLowerCase()==="d")keys.current.right=false;if(e.key==="ArrowUp"||e.key.toLowerCase()==="w"||e.key===" ")keys.current.jump=false};window.addEventListener("keydown",down);window.addEventListener("keyup",up);return()=>{window.removeEventListener("keydown",down);window.removeEventListener("keyup",up)}},[restart]);
  useEffect(()=>{let frame=0,last=performance.now(),lastHud=0;const ctx=canvas.current?.getContext("2d");if(!ctx)return;const hurt=()=>{const w=world.current;if(w.invincible>0)return;w.hearts--;setHearts(w.hearts);audio.play("error");if(w.hearts<=0){setGamePhase("over");return}w.x=w.checkpoint.x;w.y=w.checkpoint.y;w.vx=0;w.vy=0;w.invincible=100};const loop=(now:number)=>{const dt=Math.min(1.8,(now-last)/16.67);last=now;const w=world.current;if(phaseRef.current==="playing"){const accel=.72*dt;if(keys.current.left)w.vx-=accel;if(keys.current.right)w.vx+=accel;if(!keys.current.left&&!keys.current.right)w.vx*=Math.pow(.78,dt);w.vx=Math.max(-6.2,Math.min(6.2,w.vx));if(keys.current.jump&&w.grounded){w.vy=-12.4;w.grounded=false;keys.current.jump=false;audio.play("navigate")}const oldY=w.y;w.vy+=.68*dt;w.vy=Math.min(15,w.vy);w.x=Math.max(0,Math.min(WORLD-28,w.x+w.vx*dt));w.y+=w.vy*dt;w.grounded=false;for(const p of PLATFORMS){if(w.vy>=0&&oldY+40<=p.y+3&&w.y+40>=p.y&&w.x+25>p.x&&w.x<p.x+p.w){w.y=p.y-40;w.vy=0;w.grounded=true;break}}if(w.y>570)hurt();if(w.x>900&&w.checkpoint.x<900)w.checkpoint={x:820,y:440};if(w.x>1820&&w.checkpoint.x<1800)w.checkpoint={x:1840,y:390};PARCELS.forEach((p,i)=>{if(!w.parcels.has(i)&&Math.abs(w.x+14-p.x)<27&&Math.abs(w.y+20-p.y)<31){w.parcels.add(i);setParcels(w.parcels.size);setScore(w.parcels.size*150);audio.play("good")}});w.hazards.forEach(h=>{h.x+=h.dir*1.65*dt;if(h.x<h.min||h.x>h.max)h.dir*=-1;if(w.x+27>h.x-15&&w.x<h.x+15&&w.y+39>h.y-19&&w.y<h.y+12)hurt()});if(w.invincible>0)w.invincible-=dt;w.camera+=(Math.max(0,Math.min(WORLD-900,w.x-320))-w.camera)*.08;if(w.x>2735){const final=3000+w.parcels.size*500+w.hearts*700;setScore(final);audio.play("complete");setGamePhase("won");setBest(old=>{const value=Math.max(old,final);try{localStorage.setItem("fairbyte:star-courier:best",String(value))}catch{}return value})}if(now-lastHud>180){setDistance(Math.min(100,Math.floor(w.x/27.35)));lastHud=now}}
      const cam=w.camera;const sky=ctx.createLinearGradient(0,0,0,520);sky.addColorStop(0,"#080d2a");sky.addColorStop(.6,"#22215d");sky.addColorStop(1,"#572b66");ctx.fillStyle=sky;ctx.fillRect(0,0,900,520);ctx.fillStyle="#fff";for(let i=0;i<90;i++){const x=((i*137-cam*.08)%1000+1000)%1000-50,y=(i*83)%330;ctx.globalAlpha=.25+(i%7)/10;ctx.fillRect(x,y,i%5===0?2:1,i%5===0?2:1)}ctx.globalAlpha=1;ctx.fillStyle="#f7ddab";ctx.beginPath();ctx.arc(735-cam*.03,92,57,0,Math.PI*2);ctx.fill();ctx.fillStyle="#0f1435";ctx.beginPath();ctx.arc(756-cam*.03,75,51,0,Math.PI*2);ctx.fill();for(let layer=0;layer<3;layer++){ctx.fillStyle=["#171844","#22204e","#2e2254"][layer];for(let i=0;i<13;i++){const x=((i*110-cam*(.12+layer*.08))%1500+1500)%1500-150;const h=60+((i*47+layer*31)%150);ctx.fillRect(x,470-h,82,h);ctx.fillStyle="#90dcff55";for(let wy=480-h;wy<450;wy+=22)ctx.fillRect(x+12+(wy%3)*15,wy,5,7);ctx.fillStyle=["#171844","#22204e","#2e2254"][layer]}}
      ctx.save();ctx.translate(-cam,0);PLATFORMS.forEach(p=>{ctx.fillStyle="#20263b";ctx.fillRect(p.x,p.y,p.w,p.h);ctx.fillStyle="#6268a0";ctx.fillRect(p.x,p.y,p.w,6);ctx.fillStyle="#111526";for(let x=p.x+15;x<p.x+p.w;x+=34)ctx.fillRect(x,p.y+15,18,5)});PARCELS.forEach((p,i)=>{if(w.parcels.has(i))return;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(now/600);ctx.fillStyle="#ffd65c";ctx.shadowColor="#ffd65c";ctx.shadowBlur=18;ctx.fillRect(-10,-10,20,20);ctx.fillStyle="#5f4710";ctx.fillRect(-2,-10,4,20);ctx.restore()});w.hazards.forEach(h=>{ctx.fillStyle="#ff557e";ctx.shadowColor="#ff557e";ctx.shadowBlur=15;ctx.beginPath();ctx.arc(h.x,h.y,16,0,Math.PI*2);ctx.fill();ctx.fillStyle="#241025";ctx.fillRect(h.x-8,h.y-4,5,5);ctx.fillRect(h.x+3,h.y-4,5,5)});ctx.fillStyle="#9af4ff";ctx.shadowColor="#9af4ff";ctx.shadowBlur=22;ctx.fillRect(2732,332,8,108);ctx.beginPath();ctx.arc(2736,330,24+Math.sin(now/150)*5,0,Math.PI*2);ctx.strokeStyle="#9af4ff";ctx.lineWidth=5;ctx.stroke();ctx.globalAlpha=w.invincible>0&&Math.floor(w.invincible/5)%2===0?.25:1;ctx.translate(w.x,w.y);ctx.fillStyle="#e9f4ff";ctx.shadowColor="#8cefff";ctx.shadowBlur=12;ctx.fillRect(4,9,20,23);ctx.fillStyle="#69e7ff";ctx.fillRect(7,0,15,14);ctx.fillStyle="#111b35";ctx.fillRect(w.vx<0?8:17,5,4,4);ctx.fillStyle="#ffcc52";ctx.fillRect(0,15,6,14);ctx.fillStyle="#ff6c82";ctx.fillRect(5,32,7,8);ctx.fillRect(18,32,7,8);ctx.restore();ctx.globalAlpha=1;ctx.shadowBlur=0;ctx.fillStyle="#080b18bb";ctx.fillRect(18,18,245,42);ctx.fillStyle="#9ceeff";ctx.font="900 11px Arial";ctx.fillText(`ROUTE ${Math.floor(w.x)} / ${WORLD}   PARCELS ${w.parcels.size}/${PARCELS.length}`,34,44);frame=requestAnimationFrame(loop)};frame=requestAnimationFrame(loop);return()=>cancelAnimationFrame(frame)},[audio]);
  const pressLeft=useCallback(()=>{keys.current.left=true},[]);const pressRight=useCallback(()=>{keys.current.right=true},[]);const pressJump=useCallback(()=>{keys.current.jump=true},[]);const releaseLeft=useCallback(()=>{keys.current.left=false},[]);const releaseRight=useCallback(()=>{keys.current.right=false},[]);const releaseJump=useCallback(()=>{keys.current.jump=false},[]);const controls=<><button onPointerDown={pressLeft} onPointerUp={releaseLeft} onPointerLeave={releaseLeft} onPointerCancel={releaseLeft} aria-label="Run left">←</button><button onPointerDown={pressJump} onPointerUp={releaseJump} onPointerLeave={releaseJump} onPointerCancel={releaseJump} aria-label="Jump">JUMP</button><button onPointerDown={pressRight} onPointerUp={releaseRight} onPointerLeave={releaseRight} onPointerCancel={releaseRight} aria-label="Run right">→</button></>;
  return <ClassicFrame number="008" title="Star Courier" subtitle="One courier. Nine lost parcels. A midnight route across the lunar rooftops." accent="#9af4ff" score={score} best={best} status={`${distance}% route · ${parcels}/9 parcels · ${"◆".repeat(hearts)}${"◇".repeat(3-hearts)}`} sound={audio.enabled} onSound={audio.toggle} onRestart={restart} objective="Reach the launch beacon. Recover as many gold parcels as you can along the way." instructions={["Run with A/D or ←/→.","Jump with W, ↑, or Space.","Avoid red sentries; checkpoints activate along the route."]} controls={controls}>
    <div className={classic.boardWrap}><canvas ref={canvas} width={900} height={520} className={classic.canvas} aria-label="Star Courier side-scrolling platform game"/><span className={classic.hint}>MOON ROUTE · BEACON 2.8 KM</span>{phase!=="playing"&&<div className={classic.overlay}><div><span>{phase==="won"?"DELIVERY COMPLETE":phase==="over"?"COURIER OFFLINE":"ROUTE CHANNEL 08"}</span><h2>{phase==="won"?"Beacon reached.":phase==="over"?"Route failed.":"Run the rooftops."}</h2><p>A compact original platform route with nine parcels, four sentries, and two checkpoints.</p><button onClick={restart}>{phase==="ready"?"START DELIVERY":"RUN AGAIN"}</button></div></div>}</div>
  </ClassicFrame>;
}
