"use client";

import {useCallback,useEffect,useRef,useState} from "react";
import ClassicFrame from "../classics/ClassicFrame";
import classic from "../classics/classic.module.css";
import {useGameAudio} from "../../useGameAudio";

type Point={x:number;y:number};type Phase="ready"|"playing"|"over";const W=24,H=16,S=30;const same=(a:Point,b:Point)=>a.x===b.x&&a.y===b.y;const id=(p:Point)=>`${p.x},${p.y}`;
type World={coil:Point[];dir:Point;next:Point;charge:Point;blocks:Point[];collected:number};
const freePoint=(occupied:Set<string>):Point=>{for(let i=0;i<300;i++){const p={x:Math.floor(Math.random()*W),y:Math.floor(Math.random()*H)};if(!occupied.has(id(p)))return p}return{x:2,y:2}};
const fresh=():World=>({coil:[{x:7,y:8},{x:6,y:8},{x:5,y:8}],dir:{x:1,y:0},next:{x:1,y:0},charge:{x:17,y:8},blocks:[],collected:0});

export default function Coilfield(){
  const audio=useGameAudio();const canvas=useRef<HTMLCanvasElement>(null);const world=useRef<World>(fresh());const phaseRef=useRef<Phase>("ready");const [phase,setPhase]=useState<Phase>("ready");const [score,setScore]=useState(0);const scoreRef=useRef(0);const [best,setBest]=useState(0);const [length,setLength]=useState(3);const [field,setField]=useState(1);
  const setGamePhase=(p:Phase)=>{phaseRef.current=p;setPhase(p)};useEffect(()=>{const timer=window.setTimeout(()=>{try{setBest(Number(localStorage.getItem("fairbyte:coilfield:best")||0))}catch{}},0);return()=>window.clearTimeout(timer)},[]);
  const restart=useCallback(()=>{audio.play("navigate");world.current=fresh();scoreRef.current=0;setScore(0);setLength(3);setField(1);setGamePhase("playing")},[audio]);
  const steer=useCallback((next:Point)=>{const w=world.current;if(next.x===-w.dir.x&&next.y===-w.dir.y)return;w.next=next;if(phaseRef.current==="ready")restart()},[restart]);
  useEffect(()=>{const onKey=(e:KeyboardEvent)=>{const moves:Record<string,Point>={ArrowLeft:{x:-1,y:0},a:{x:-1,y:0},ArrowRight:{x:1,y:0},d:{x:1,y:0},ArrowUp:{x:0,y:-1},w:{x:0,y:-1},ArrowDown:{x:0,y:1},s:{x:0,y:1}};const move=moves[e.key]||moves[e.key.toLowerCase()];if(move){e.preventDefault();steer(move)}if((e.key==="Enter"||e.key===" ")&&phaseRef.current!=="playing")restart()};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[restart,steer]);
  useEffect(()=>{const tick=()=>{if(phaseRef.current!=="playing")return;const w=world.current;w.dir=w.next;const head={x:(w.coil[0].x+w.dir.x+W)%W,y:(w.coil[0].y+w.dir.y+H)%H};if(w.coil.some((p,i)=>i>0&&same(p,head))||w.blocks.some(p=>same(p,head))){audio.play("error");setGamePhase("over");setBest(old=>{const value=Math.max(old,scoreRef.current);try{localStorage.setItem("fairbyte:coilfield:best",String(value))}catch{}return value});return}w.coil.unshift(head);if(same(head,w.charge)){w.collected++;scoreRef.current+=100+(w.collected-1)*10;setScore(scoreRef.current);setLength(w.coil.length);audio.play(w.collected%4===0?"success":"tap");const occupied=new Set([...w.coil,...w.blocks].map(id));if(w.collected%4===0){w.blocks.push(freePoint(occupied));occupied.add(id(w.blocks.at(-1)!));w.blocks.push(freePoint(occupied));setField(Math.floor(w.collected/4)+1)}w.charge=freePoint(new Set([...w.coil,...w.blocks].map(id)))}else w.coil.pop()};const timer=window.setInterval(tick,Math.max(72,132-world.current.collected*2));return()=>window.clearInterval(timer)},[audio,score]);
  useEffect(()=>{let frame=0;const ctx=canvas.current?.getContext("2d");if(!ctx)return;const draw=()=>{const w=world.current;ctx.fillStyle="#05080c";ctx.fillRect(0,0,W*S,H*S);ctx.strokeStyle="#162125";ctx.lineWidth=1;for(let x=0;x<=W;x++){ctx.beginPath();ctx.moveTo(x*S,0);ctx.lineTo(x*S,H*S);ctx.stroke()}for(let y=0;y<=H;y++){ctx.beginPath();ctx.moveTo(0,y*S);ctx.lineTo(W*S,y*S);ctx.stroke()}w.blocks.forEach((p,i)=>{ctx.fillStyle="#ff416c";ctx.shadowColor="#ff416c";ctx.shadowBlur=10;ctx.fillRect(p.x*S+5,p.y*S+5,S-10,S-10);ctx.fillStyle="#19070c";ctx.font="bold 12px Arial";ctx.textAlign="center";ctx.fillText(i%2?"−":"+",p.x*S+15,p.y*S+20)});w.coil.forEach((p,i)=>{const a=Math.max(.25,1-i/w.coil.length*.65);ctx.globalAlpha=a;ctx.fillStyle=i===0?"#eaff69":"#4de7b5";ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=i===0?18:8;ctx.beginPath();ctx.roundRect(p.x*S+3,p.y*S+3,S-6,S-6,7);ctx.fill();if(i===0){ctx.fillStyle="#092017";ctx.fillRect(p.x*S+9,p.y*S+9,4,4);ctx.fillRect(p.x*S+18,p.y*S+9,4,4)}});ctx.globalAlpha=1;const pulse=2+Math.sin(Date.now()/90)*2;ctx.strokeStyle="#f8f4ff";ctx.fillStyle="#d9b7ff";ctx.shadowColor="#d9b7ff";ctx.shadowBlur=22;ctx.lineWidth=3;ctx.beginPath();ctx.arc(w.charge.x*S+15,w.charge.y*S+15,8+pulse,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.shadowBlur=0;frame=requestAnimationFrame(draw)};frame=requestAnimationFrame(draw);return()=>cancelAnimationFrame(frame)},[]);
  const controls=<><button onClick={()=>steer({x:-1,y:0})} aria-label="Turn left">←</button><button onClick={()=>steer({x:0,y:-1})} aria-label="Turn up">↑</button><button onClick={()=>steer({x:0,y:1})} aria-label="Turn down">↓</button><button onClick={()=>steer({x:1,y:0})} aria-label="Turn right">→</button></>;
  return <ClassicFrame number="011" title="Coilfield" subtitle="A runaway signal grows longer every time it finds a live charge." accent="#eaff69" score={score} best={best} status={`length ${length} · field ${field}`} sound={audio.enabled} onSound={audio.toggle} onRestart={restart} objective="Guide the signal coil into charge cells without crossing your tail or dead pixels." instructions={["Turn with arrows or W/A/S/D.","The field wraps at every edge.","Every fourth charge creates two permanent dead pixels."]} controls={controls}>
    <div className={classic.boardWrap}><canvas ref={canvas} width={W*S} height={H*S} className={classic.canvas} aria-label="Coilfield game grid"/><span className={classic.hint}>WRAP FIELD · EDGES CONNECT</span>{phase!=="playing"&&<div className={classic.overlay}><div><span>{phase==="over"?"SIGNAL CROSSED":"COIL CHANNEL 11"}</span><h2>{phase==="over"?"Field collapsed.":"Grow the current."}</h2><p>The edges connect. The coil remembers every move. Dead pixels multiply.</p><button onClick={restart}>{phase==="ready"?"CHARGE COIL":"RECONNECT"}</button></div></div>}</div>
  </ClassicFrame>;
}
