"use client";

import {useCallback,useEffect,useRef,useState} from "react";
import DeepFrame from "../shared/DeepFrame";
import deep from "../shared/deep.module.css";
import {useGameAudio} from "../../useGameAudio";
import styles from "./game.module.css";

type Mode="solo"|"versus";
type Phase="ready"|"playing"|"over";
type Player={x:number;y:number;vx:number;vy:number;color:string;score:number;dash:number;stun:number;shield:number;carrying:boolean};
type Orb={x:number;y:number;active:boolean};
type Pickup={x:number;y:number;kind:"shield"|"haste";life:number};
type World={phase:Phase;p1:Player;p2:Player;orb:Orb;pickups:Pickup[];round:number;flash:number;hazard:number;spawn:number;winner:number};
type Key="p1u"|"p1d"|"p1l"|"p1r"|"p1dash"|"p2u"|"p2d"|"p2l"|"p2r"|"p2dash";
const W=900,H=560,GOAL=5;
const makePlayer=(x:number,color:string):Player=>({x,y:H/2,vx:0,vy:0,color,score:0,dash:0,stun:0,shield:0,carrying:false});
const fresh=():World=>({phase:"ready",p1:makePlayer(180,"#4ff0ff"),p2:makePlayer(720,"#ff4da0"),orb:{x:W/2,y:H/2,active:true},pickups:[],round:1,flash:0,hazard:0,spawn:400,winner:0});
const clamp=(value:number,min:number,max:number)=>Math.max(min,Math.min(max,value));
const dist=(a:{x:number;y:number},b:{x:number;y:number})=>Math.hypot(a.x-b.x,a.y-b.y);

export default function TwofoldArena(){
  const audio=useGameAudio();const canvas=useRef<HTMLCanvasElement>(null);const world=useRef<World>(fresh());const keys=useRef<Record<Key,boolean>>({p1u:false,p1d:false,p1l:false,p1r:false,p1dash:false,p2u:false,p2d:false,p2l:false,p2r:false,p2dash:false});
  const modeRef=useRef<Mode>("solo");const [mode,setModeState]=useState<Mode>("solo");const [phase,setPhase]=useState<Phase>("ready");const [left,setLeft]=useState(0);const [right,setRight]=useState(0);const [soloWins,setSoloWins]=useState(0);const [flash,setFlash]=useState("");
  useEffect(()=>{const timer=window.setTimeout(()=>{try{setSoloWins(Number(localStorage.getItem("fairbyte:twofold:solo-wins")||0))}catch{}},0);return()=>window.clearTimeout(timer)},[]);
  const setMode=(value:Mode)=>{modeRef.current=value;setModeState(value);audio.play("navigate")};
  const restart=useCallback(()=>{world.current=fresh();world.current.phase="playing";Object.keys(keys.current).forEach(key=>{keys.current[key as Key]=false});setPhase("playing");setLeft(0);setRight(0);setFlash("FIRST TO FIVE");window.setTimeout(()=>setFlash(""),900);audio.play("success")},[audio]);
  const setKey=useCallback((key:Key,value:boolean)=>{keys.current[key]=value},[]);
  useEffect(()=>{const down=(event:KeyboardEvent)=>{const k=event.key.toLowerCase();if(["w","a","s","d","f","arrowup","arrowdown","arrowleft","arrowright","/","enter"].includes(k))event.preventDefault();if(k==="w")setKey("p1u",true);if(k==="s")setKey("p1d",true);if(k==="a")setKey("p1l",true);if(k==="d")setKey("p1r",true);if(k==="f")setKey("p1dash",true);if(k==="arrowup")setKey("p2u",true);if(k==="arrowdown")setKey("p2d",true);if(k==="arrowleft")setKey("p2l",true);if(k==="arrowright")setKey("p2r",true);if(k==="/")setKey("p2dash",true);if(k==="enter"&&world.current.phase!=="playing")restart()};const up=(event:KeyboardEvent)=>{const k=event.key.toLowerCase();if(k==="w")setKey("p1u",false);if(k==="s")setKey("p1d",false);if(k==="a")setKey("p1l",false);if(k==="d")setKey("p1r",false);if(k==="f")setKey("p1dash",false);if(k==="arrowup")setKey("p2u",false);if(k==="arrowdown")setKey("p2d",false);if(k==="arrowleft")setKey("p2l",false);if(k==="arrowright")setKey("p2r",false);if(k==="/")setKey("p2dash",false)};window.addEventListener("keydown",down);window.addEventListener("keyup",up);return()=>{window.removeEventListener("keydown",down);window.removeEventListener("keyup",up)}},[restart,setKey]);

  useEffect(()=>{let frame=0,last=performance.now();const ctx=canvas.current?.getContext("2d");if(!ctx)return;const resetRound=(winner:1|2)=>{const w=world.current;const scorer=winner===1?w.p1:w.p2;scorer.score++;setLeft(w.p1.score);setRight(w.p2.score);audio.play("complete");if(scorer.score>=GOAL){w.phase="over";w.winner=winner;setPhase("over");if(modeRef.current==="solo"&&winner===1)setSoloWins(old=>{const value=old+1;try{localStorage.setItem("fairbyte:twofold:solo-wins",String(value))}catch{}return value});return}w.round++;w.p1.x=180;w.p1.y=H/2;w.p1.vx=w.p1.vy=0;w.p1.carrying=false;w.p2.x=720;w.p2.y=H/2;w.p2.vx=w.p2.vy=0;w.p2.carrying=false;w.orb={x:W/2,y:H/2,active:true};w.flash=70;setFlash(winner===1?"CYAN SCORES":"MAGENTA SCORES");window.setTimeout(()=>setFlash(""),750)};
    const loop=(now:number)=>{const dt=Math.min(1.8,(now-last)/16.67);last=now;const w=world.current;if(w.phase==="playing"){const control=(p:Player,u:boolean,d:boolean,l:boolean,r:boolean,dash:boolean)=>{if(p.stun>0){p.stun-=dt;return}const accel=.55*(p.shield>0?1.08:1);if(u)p.vy-=accel*dt;if(d)p.vy+=accel*dt;if(l)p.vx-=accel*dt;if(r)p.vx+=accel*dt;if(dash&&p.dash<=0){const mag=Math.hypot(p.vx,p.vy)||1;p.vx=p.vx/mag*11;p.vy=p.vy/mag*11;p.dash=105;audio.play("tap")}p.dash=Math.max(0,p.dash-dt);p.shield=Math.max(0,p.shield-dt);p.vx*=Math.pow(.89,dt);p.vy*=Math.pow(.89,dt);p.x=clamp(p.x+p.vx*dt,28,W-28);p.y=clamp(p.y+p.vy*dt,45,H-35)};
      control(w.p1,keys.current.p1u,keys.current.p1d,keys.current.p1l,keys.current.p1r,keys.current.p1dash);
      if(modeRef.current==="versus")control(w.p2,keys.current.p2u,keys.current.p2d,keys.current.p2l,keys.current.p2r,keys.current.p2dash);else{const target=w.p2.carrying?{x:55,y:H/2}:w.orb.active?w.orb:w.p1;const dx=target.x-w.p2.x,dy=target.y-w.p2.y;control(w.p2,dy<-12,dy>12,dx<-12,dx>12,dist(w.p2,target)>230&&w.p2.dash<=0)}
      if(dist(w.p1,w.p2)<45){const dx=w.p2.x-w.p1.x,dy=w.p2.y-w.p1.y,len=Math.hypot(dx,dy)||1,power=(Math.hypot(w.p1.vx,w.p1.vy)+Math.hypot(w.p2.vx,w.p2.vy))*.28+.6;if(w.p1.shield<=0){w.p1.vx-=dx/len*power;w.p1.vy-=dy/len*power}if(w.p2.shield<=0){w.p2.vx+=dx/len*power;w.p2.vy+=dy/len*power}const dasher=w.p1.dash>75?w.p1:w.p2.dash>75?w.p2:null;if(dasher){const other=dasher===w.p1?w.p2:w.p1;if(other.shield<=0)other.stun=32;if(other.carrying){other.carrying=false;w.orb={x:other.x,y:other.y,active:true}}}}
      for(const p of [w.p1,w.p2])if(w.orb.active&&dist(p,w.orb)<28){p.carrying=true;w.orb.active=false;audio.play("good")}const carrier=w.p1.carrying?w.p1:w.p2.carrying?w.p2:null;if(carrier){w.orb.x=carrier.x;w.orb.y=carrier.y-27;if(carrier===w.p1&&carrier.x>842)resetRound(1);if(carrier===w.p2&&carrier.x<58)resetRound(2)}
      w.hazard=(w.hazard+dt)%330;const hazardX=450+Math.sin(w.hazard/45)*145;if(Math.abs(w.hazard-165)<1.2){for(const p of [w.p1,w.p2])if(Math.abs(p.x-hazardX)<25&&p.shield<=0)p.stun=48}
      w.spawn-=dt;if(w.spawn<=0&&w.pickups.length<2){w.pickups.push({x:190+Math.random()*520,y:90+Math.random()*380,kind:Math.random()>.5?"shield":"haste",life:520});w.spawn=330}w.pickups.forEach(item=>item.life-=dt);for(const p of [w.p1,w.p2]){const item=w.pickups.find(value=>dist(p,value)<26);if(item){p.shield=item.kind==="shield"?300:p.shield;p.dash=item.kind==="haste"?0:p.dash;item.life=0;audio.play("success")}}w.pickups=w.pickups.filter(item=>item.life>0);w.flash=Math.max(0,w.flash-dt)}
      ctx.fillStyle="#070514";ctx.fillRect(0,0,W,H);const gradient=ctx.createLinearGradient(0,0,W,0);gradient.addColorStop(0,"#071c2a");gradient.addColorStop(.48,"#110922");gradient.addColorStop(.52,"#18091b");gradient.addColorStop(1,"#2b071d");ctx.fillStyle=gradient;ctx.fillRect(0,0,W,H);ctx.strokeStyle="#ffffff0f";for(let x=0;x<W;x+=50){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=50){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.strokeStyle="#7f6ba866";ctx.setLineDash([8,12]);ctx.beginPath();ctx.moveTo(W/2,0);ctx.lineTo(W/2,H);ctx.stroke();ctx.setLineDash([]);
      ctx.fillStyle="#4ff0ff22";ctx.fillRect(W-52,135,38,290);ctx.strokeStyle="#4ff0ff";ctx.strokeRect(W-52,135,38,290);ctx.fillStyle="#ff4da022";ctx.fillRect(14,135,38,290);ctx.strokeStyle="#ff4da0";ctx.strokeRect(14,135,38,290);const hazardX=450+Math.sin(w.hazard/45)*145;ctx.strokeStyle="#ffde72";ctx.globalAlpha=.35+Math.abs(Math.sin(w.hazard/18))*.45;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(hazardX,55);ctx.lineTo(hazardX,H-30);ctx.stroke();ctx.globalAlpha=1;
      w.pickups.forEach(item=>{ctx.fillStyle=item.kind==="shield"?"#ffde72":"#a274ff";ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=15;ctx.beginPath();ctx.arc(item.x,item.y,10,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0});if(w.orb.active){ctx.fillStyle="#fff";ctx.shadowColor="#fff";ctx.shadowBlur=22;ctx.beginPath();ctx.arc(w.orb.x,w.orb.y,11,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}
      const drawPlayer=(p:Player,index:number)=>{ctx.save();ctx.translate(p.x,p.y);ctx.fillStyle=p.color;ctx.shadowColor=p.color;ctx.shadowBlur=18;ctx.beginPath();ctx.arc(0,0,21,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#080614";ctx.font="bold 13px Arial";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(String(index),0,1);if(p.shield>0){ctx.strokeStyle="#ffde72";ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,29,0,Math.PI*2);ctx.stroke()}if(p.stun>0){ctx.fillStyle="#fff";ctx.fillText("×",0,-32)}ctx.restore()};drawPlayer(w.p1,1);drawPlayer(w.p2,2);frame=requestAnimationFrame(loop)};frame=requestAnimationFrame(loop);return()=>cancelAnimationFrame(frame)},[audio]);

  const release=(key:Key)=>setKey(key,false);const touch=<div className={styles.touch}><button aria-label="Move left" onPointerDown={()=>setKey("p1l",true)} onPointerUp={()=>release("p1l")} onPointerLeave={()=>release("p1l")} onPointerCancel={()=>release("p1l")}>←</button><button aria-label="Move up" onPointerDown={()=>setKey("p1u",true)} onPointerUp={()=>release("p1u")} onPointerLeave={()=>release("p1u")} onPointerCancel={()=>release("p1u")}>↑</button><button aria-label="Move down" onPointerDown={()=>setKey("p1d",true)} onPointerUp={()=>release("p1d")} onPointerLeave={()=>release("p1d")} onPointerCancel={()=>release("p1d")}>↓</button><button aria-label="Move right" onPointerDown={()=>setKey("p1r",true)} onPointerUp={()=>release("p1r")} onPointerLeave={()=>release("p1r")} onPointerCancel={()=>release("p1r")}>→</button><button aria-label="Dash" onPointerDown={()=>setKey("p1dash",true)} onPointerUp={()=>release("p1dash")} onPointerLeave={()=>release("p1dash")} onPointerCancel={()=>release("p1dash")}>DASH</button></div>;
  const side=<><div className={styles.mode}><button className={mode==="solo"?styles.on:""} onClick={()=>setMode("solo")} disabled={phase==="playing"}>SOLO VS AI</button><button className={mode==="versus"?styles.on:""} onClick={()=>setMode("versus")} disabled={phase==="playing"}>LOCAL 2P</button></div><div className={styles.rules}>Carry the white core into the opponent gate. A high-speed dash knocks the core loose. Gold pickups grant a shield; violet resets dash.</div></>;
  return <DeepFrame number="015" title="Twofold Arena" collection="SOLO + LOCAL MULTIPLAYER" tagline="One screen. Two gates. No safe side." accent="#4ff0ff" accent2="#ff4da0" status={phase==="playing"?`ROUND ${left+right+1} · FIRST TO ${GOAL}`:phase.toUpperCase()} stats={[{label:"CYAN",value:left},{label:"MAGENTA",value:right},{label:"SOLO WINS",value:soloWins}]} sound={audio.enabled} onSound={audio.toggle} onRestart={restart} objective="Steal the core and carry it across the rival goal line five times." instructions={["Player 1 uses WASD + F to dash. Player 2 uses arrows + /.","Dash into a carrier to stun them and knock the core loose.","Time crossings around the moving fault beam and hunt shield pickups."]} controls={touch} side={side}>
    <div className={`${deep.board} ${styles.arena}`}><canvas ref={canvas} width={W} height={H} className={deep.canvas} aria-label="Twofold neon objective arena"/><div className={styles.scoreline}><div><strong>{left}</strong><span>CYAN</span></div><span>ROUND {left+right+1}</span><div><span>MAGENTA</span><strong>{right}</strong></div></div>{flash&&<div className={styles.roundFlash}>{flash}</div>}{phase!=="playing"&&<div className={deep.overlay}><div><span className={styles.badge}>{phase==="over"?`${left>right?"CYAN":"MAGENTA"} WINS THE MATCH`:"GAME 015 · TWO-FOLD COMBAT"}</span><h2>{phase==="over"?"Run it back.":"Rivalry, installed."}</h2><p>Objective play, dash tackles, carry steals, timed hazards, pickups, solo AI, and true two-player keyboard play.</p><button onClick={restart}>{phase==="ready"?"ENTER ARENA":"REMATCH"}</button></div></div>}</div>
  </DeepFrame>
}
