"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import DeepFrame from "../shared/DeepFrame";
import {useGameAudio} from "../../useGameAudio";
import styles from "./game.module.css";

type Rule={id:string;label:string;explain:string;test:(a:number[])=>boolean};
const RULES:Rule[]=[
  {id:"ascending",label:"Every value rises from left to right.",explain:"Accepted specimens are strictly ascending.",test:a=>a[0]<a[1]&&a[1]<a[2]},
  {id:"even-sum",label:"The three values have an even total.",explain:"Accepted specimens add to an even number.",test:a=>(a[0]+a[1]+a[2])%2===0},
  {id:"distinct",label:"No value appears more than once.",explain:"Accepted specimens contain three different values.",test:a=>new Set(a).size===3},
  {id:"middle-high",label:"The center value is the largest.",explain:"Accepted specimens peak in the middle position.",test:a=>a[1]>a[0]&&a[1]>a[2]},
  {id:"one-odd",label:"Exactly one value is odd.",explain:"Accepted specimens contain one odd and two even values.",test:a=>a.filter(n=>n%2===1).length===1},
  {id:"edge-match",label:"The first and last values match.",explain:"Accepted specimens begin and end with the same value.",test:a=>a[0]===a[2]},
  {id:"high-total",label:"The values total at least twelve.",explain:"Accepted specimens have a sum of twelve or more.",test:a=>a[0]+a[1]+a[2]>=12},
  {id:"step",label:"Each value changes by the same amount.",explain:"Accepted specimens form an arithmetic sequence.",test:a=>a[1]-a[0]===a[2]-a[1]},
  {id:"contains-three",label:"At least one value is exactly three.",explain:"Accepted specimens contain a three in any position.",test:a=>a.includes(3)},
  {id:"outer-greater",label:"The outside values outweigh the center.",explain:"Accepted specimens have first plus last greater than the middle.",test:a=>a[0]+a[2]>a[1]},
];
const mulberry=(seed:number)=>()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296};
const DAILY_EPOCH=Math.floor(Date.UTC(2026,7,1)/86400000)-1;
type Puzzle={rule:Rule;choices:Rule[];samples:number[][]};
function shuffle<T>(items:T[],rand:()=>number){const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(rand()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function makePuzzle(seed:number):Puzzle{const rand=mulberry(seed||7319);const rule=RULES[Math.floor(rand()*RULES.length)];const decoys=shuffle(RULES.filter(r=>r.id!==rule.id),rand).slice(0,3);const pool:number[][]=[];for(let a=0;a<7;a++)for(let b=0;b<7;b++)for(let c=0;c<7;c++)pool.push([a,b,c]);const randomized=shuffle(pool,rand);const samples:number[][]=[];const add=(sample:number[]|undefined)=>{if(sample&&!samples.some(existing=>existing.join()===sample.join()))samples.push(sample)};decoys.forEach(decoy=>add(randomized.find(sample=>rule.test(sample)!==decoy.test(sample))));add(randomized.find(sample=>rule.test(sample)));add(randomized.find(sample=>!rule.test(sample)));for(const sample of randomized){if(samples.length>=12)break;add(sample)}const choices=shuffle([rule,...decoys],rand);return{rule,choices,samples:shuffle(samples,rand)}}
type Stored={streak:number;max:number;played:number;solved:number;lastWin:number;completedDay:number;dailyResult?:{probes:{index:number;accepted:boolean}[];won:boolean}};
const EMPTY:Stored={streak:0,max:0,played:0,solved:0,lastWin:-1,completedDay:-1};
const cleanInt=(value:unknown,fallback=0)=>typeof value==="number"&&Number.isFinite(value)?Math.max(0,Math.floor(value)):fallback;
function loadStats(raw:string):Stored{try{const value=JSON.parse(raw) as Partial<Stored>;const result=value.dailyResult,probes=Array.isArray(result?.probes)?result.probes.filter(item=>item&&Number.isInteger(item.index)&&item.index>=0&&item.index<12&&typeof item.accepted==="boolean").slice(0,6):[];return{streak:cleanInt(value.streak),max:cleanInt(value.max),played:cleanInt(value.played),solved:cleanInt(value.solved),lastWin:typeof value.lastWin==="number"&&Number.isFinite(value.lastWin)?Math.floor(value.lastWin):-1,completedDay:typeof value.completedDay==="number"&&Number.isFinite(value.completedDay)?Math.floor(value.completedDay):-1,...(result&&typeof result.won==="boolean"?{dailyResult:{probes,won:result.won}}:{})}}catch{return EMPTY}}

export default function BlackBoxDaily(){
  const audio=useGameAudio();const [day,setDay]=useState(0);const [mode,setMode]=useState<"daily"|"practice">("daily");const [practiceSeed,setPracticeSeed]=useState(8117);const [probes,setProbes]=useState<{index:number;accepted:boolean}[]>([]);const [answer,setAnswer]=useState<string|null>(null);const [stats,setStats]=useState<Stored>(EMPTY);const [notice,setNotice]=useState("");
  useEffect(()=>{const timer=window.setTimeout(()=>{setDay(Math.floor(Date.now()/86400000));try{setStats(loadStats(localStorage.getItem("fairbyte:black-box:stats")||"{}"))}catch{}},0);return()=>window.clearTimeout(timer)},[]);
  const seed=mode==="daily"?(day||20800):practiceSeed;const puzzle=useMemo(()=>makePuzzle(seed*7919+17),[seed]);const complete=answer!==null;const won=answer===puzzle.rule.id;
  useEffect(()=>{if(mode!=="daily"||!day||stats.completedDay!==day||!stats.dailyResult)return;const timer=window.setTimeout(()=>{setProbes(stats.dailyResult!.probes);setAnswer(stats.dailyResult!.won?puzzle.rule.id:"lost")},0);return()=>window.clearTimeout(timer)},[day,mode,puzzle.rule.id,stats.completedDay,stats.dailyResult]);
  const reset=useCallback(()=>{audio.play("reset");setProbes([]);setAnswer(null);setNotice("");if(mode==="practice")setPracticeSeed(v=>v+Math.floor(Math.random()*9000)+1)},[audio,mode]);
  const switchMode=(next:"daily"|"practice")=>{audio.play("navigate");setMode(next);setProbes([]);setAnswer(null);setNotice("");if(next==="practice")setPracticeSeed(day*13+97)};
  const probe=(index:number)=>{if(complete||probes.length>=6||probes.some(p=>p.index===index))return;const accepted=puzzle.rule.test(puzzle.samples[index]);audio.play(accepted?"good":"error");setProbes(old=>[...old,{index,accepted}])};
  const choose=(id:string)=>{if(complete)return;const success=id===puzzle.rule.id;audio.play(success?"complete":"error");setAnswer(id);if(mode==="daily"&&day&&stats.completedDay!==day){const streak=success?(stats.lastWin===day-1?stats.streak+1:1):0;const next:Stored={streak,max:Math.max(stats.max,streak),played:stats.played+1,solved:stats.solved+(success?1:0),lastWin:success?day:stats.lastWin,completedDay:day,dailyResult:{probes,won:success}};setStats(next);try{localStorage.setItem("fairbyte:black-box:stats",JSON.stringify(next))}catch{}}};
  const share=async()=>{const grid=probes.map(p=>p.accepted?"🟩":"🟥").join("");const text=`Black Box Daily #${day-DAILY_EPOCH} ${won?"SOLVED":"MISSED"}\n${grid||"⬛"} ${probes.length}/6\nhttps://play.fairbyte.us/games/black-box-daily/`;const shareFn=(navigator as unknown as {share?: (data:{title?:string;text?:string})=>Promise<void>}).share;try{if(shareFn)await shareFn.call(navigator,{title:"Black Box Daily",text});else await navigator.clipboard.writeText(text);setNotice(shareFn?"SHARED":"RESULT COPIED")}catch{setNotice("SHARE CANCELLED")}};
  const score=complete&&won?Math.max(100,1000-probes.length*110):0;const side=<div className={styles.sideStats}><div><b>{stats.streak}</b><span>STREAK</span></div><div><b>{stats.max}</b><span>BEST</span></div><div><b>{stats.solved}</b><span>SOLVED</span></div><div><b>{stats.played}</b><span>PLAYED</span></div></div>;
  return <DeepFrame number="012" title="Black Box Daily" collection="DAILY LOGIC" tagline="Six probes. One hidden rule. The same machine for everyone today." accent="#61f5b0" accent2="#ffcf5a" status={complete?(won?"RULE DISCOVERED":"RULE MISSED"):`${6-probes.length} PROBES REMAIN`} stats={[{label:"SCORE",value:score},{label:"STREAK",value:stats.streak},{label:"PROBES",value:`${probes.length}/6`}]} sound={audio.enabled} onSound={audio.toggle} onRestart={reset} objective="Test specimens, study what the machine accepts, then identify its hidden rule." instructions={["Probe up to six specimen sequences.","Green means accepted; red means rejected.","You get one final rule selection per daily puzzle."]} side={side}>
    <div className={styles.console}><header><span/><b>BLACK BOX / {mode==="daily"?`DAILY ${day?`#${day-DAILY_EPOCH}`:"SYNCING"}`:"PRACTICE LAB"}</b><i>DETERMINISTIC INFERENCE ENGINE</i></header><div className={styles.modebar}><button className={mode==="daily"?styles.active:""} onClick={()=>switchMode("daily")}>DAILY MACHINE</button><button className={mode==="practice"?styles.active:""} onClick={()=>switchMode("practice")}>UNLIMITED PRACTICE</button></div><div className={styles.body}><section className={styles.lab}><span>SPECIMEN INPUT</span><h2>Which sequences belong inside the box?</h2><div className={styles.specimens}>{puzzle.samples.map((sample,index)=>{const result=probes.find(p=>p.index===index);return <button key={`${seed}-${index}`} onClick={()=>probe(index)} disabled={complete||!!result||probes.length>=6} className={`${styles.specimen} ${result?(result.accepted?styles.accepted:styles.rejected):""} ${(complete||probes.length>=6)&&!result?styles.locked:""}`}>{sample.map((n,i)=><span className={styles.token} key={i}>{n}</span>)}{result&&<i>{result.accepted?"✓":"×"}</i>}</button>})}</div><div className={styles.probeCount}><span>PROBE BUDGET</span><div className={styles.probeDots}>{Array.from({length:6},(_,i)=><i key={i} className={i<probes.length?styles.used:""}/>)}</div></div></section><aside className={styles.theories}><span>THEORY BOARD</span><h3>Commit to one rule.</h3>{puzzle.choices.map(rule=><button key={rule.id} disabled={complete} onClick={()=>choose(rule.id)} className={complete?(rule.id===puzzle.rule.id?styles.correct:rule.id===answer?styles.wrong:""):""}>{rule.label}</button>)}{complete&&<div className={styles.verdict}><b>{won?"INFERENCE CONFIRMED":"MACHINE REJECTED THEORY"}</b><p>{puzzle.rule.explain}</p><button onClick={share}>SHARE RESULT</button>{mode==="practice"&&<button onClick={reset}>NEXT MACHINE</button>}{notice&&<div className={styles.shareNotice}>{notice}</div>}</div>}</aside></div></div>
  </DeepFrame>;
}
