"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import type {CSSProperties} from "react";
import DeepFrame from "../shared/DeepFrame";
import deep from "../shared/deep.module.css";
import {useGameAudio} from "../../useGameAudio";
import styles from "./game.module.css";

type CardId="slash"|"guard"|"quill"|"cinder"|"bleed"|"focus"|"mend"|"echo"|"brand"|"ward"|"gambit"|"storm";
type Card={id:CardId;name:string;cost:number;type:"attack"|"skill"|"hex";text:string;value:number};
type EnemyDef={id:string;name:string;icon:string;hp:number;attack:number;note:string;boss?:boolean};
type Phase="ready"|"map"|"battle"|"reward"|"relic"|"won"|"lost";
type Relic="Red Seal"|"Glass Nib"|"Margin Note";
type Run={phase:Phase;floor:number;hp:number;maxHp:number;deck:CardId[];relics:Relic[];enemy:EnemyDef|null;enemyHp:number;enemyBlock:number;poison:number;blight:number;heroBlock:number;energy:number;turn:number;draw:CardId[];hand:CardId[];discard:CardId[];score:number};

const CARDS:Record<CardId,Card>={
  slash:{id:"slash",name:"Ink Slash",cost:1,type:"attack",text:"Deal 7 damage.",value:7},guard:{id:"guard",name:"Margin Guard",cost:1,type:"skill",text:"Gain 7 block.",value:7},quill:{id:"quill",name:"Quick Quill",cost:0,type:"attack",text:"Deal 3. Draw 1.",value:3},cinder:{id:"cinder",name:"Cinder Line",cost:2,type:"attack",text:"Deal 15 damage.",value:15},bleed:{id:"bleed",name:"Redaction",cost:1,type:"hex",text:"Apply 4 poison.",value:4},focus:{id:"focus",name:"Fine Point",cost:1,type:"skill",text:"Gain 4 block. Draw 2.",value:4},mend:{id:"mend",name:"Bind the Page",cost:2,type:"skill",text:"Heal 6. Exhausts.",value:6},echo:{id:"echo",name:"Echo Stroke",cost:1,type:"attack",text:"Deal 4 twice.",value:4},brand:{id:"brand",name:"Ash Brand",cost:2,type:"hex",text:"Deal 8 and apply 3 poison.",value:8},ward:{id:"ward",name:"Black Ward",cost:2,type:"skill",text:"Gain 15 block.",value:15},gambit:{id:"gambit",name:"Author's Gambit",cost:1,type:"attack",text:"Deal 5 + floor × 2.",value:5},storm:{id:"storm",name:"Inkstorm",cost:3,type:"attack",text:"Deal 26 damage.",value:26}
};
const ENEMIES:EnemyDef[]=[{id:"scribe",name:"Hollow Scribe",icon:"✒",hp:38,attack:7,note:"Raises its attack every third turn."},{id:"hound",name:"Ash Hound",icon:"♞",hp:32,attack:9,note:"Fast, direct, and lightly armored."},{id:"bailiff",name:"Red Bailiff",icon:"♜",hp:55,attack:8,note:"Alternates armor and heavy strikes."},{id:"moth",name:"Archive Moth",icon:"✣",hp:44,attack:6,note:"Poison pressure punishes long fights."},{id:"abbot",name:"The Blotted Abbot",icon:"♛",hp:105,attack:11,note:"Act boss. Every fourth intent is ruinous.",boss:true},{id:"editor",name:"Final Editor",icon:"♚",hp:180,attack:14,note:"Final boss. Survive the revision.",boss:true}];
const REWARDS:CardId[]=["quill","cinder","bleed","focus","mend","echo","brand","ward","gambit","storm"];
const startRun=():Run=>({phase:"ready",floor:0,hp:55,maxHp:55,deck:["slash","slash","slash","slash","guard","guard","guard","guard","quill","bleed"],relics:[],enemy:null,enemyHp:0,enemyBlock:0,poison:0,blight:0,heroBlock:0,energy:3,turn:1,draw:[],hand:[],discard:[],score:0});
const shuffled=<T,>(items:T[])=>{const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy};
function drawCards(run:Run,count:number){let draw=[...run.draw],discard=[...run.discard];const hand=[...run.hand];for(let i=0;i<count;i++){if(!draw.length){draw=shuffled(discard);discard=[]}const card=draw.shift();if(card)hand.push(card)}return{...run,draw,discard,hand}}

export default function AshAndInk(){
  const audio=useGameAudio();const [run,setRun]=useState<Run>(startRun);const [best,setBest]=useState(0);
  useEffect(()=>{const timer=window.setTimeout(()=>{try{setBest(Number(localStorage.getItem("fairbyte:ash-ink:best")||0))}catch{}},0);return()=>window.clearTimeout(timer)},[]);
  const saveBest=useCallback((score:number)=>{setBest(old=>{const next=Math.max(old,score);try{localStorage.setItem("fairbyte:ash-ink:best",String(next))}catch{}return next})},[]);
  const restart=useCallback(()=>{const next=startRun();next.phase="map";setRun(next);audio.play("navigate")},[audio]);
  const paths=useMemo(()=>{if(run.floor===8)return[ENEMIES[5]];if(run.floor===2||run.floor===5)return[ENEMIES[4]];const base=(run.floor*2)%4;return[ENEMIES[base],ENEMIES[(base+1)%4]]},[run.floor]);
  const enterBattle=(enemy:EnemyDef)=>{setRun(old=>{const piles:{draw:CardId[];discard:CardId[];hand:CardId[]}={draw:shuffled(old.deck),discard:[],hand:[]};let value:Run={...old,phase:"battle",enemy,enemyHp:Math.round(enemy.hp*(1+old.floor*.12)),enemyBlock:0,poison:0,blight:0,heroBlock:0,energy:old.relics.includes("Glass Nib")?4:3,turn:1,...piles};value=drawCards(value,5);return value});audio.play("success")};
  const resolveWin=(value:Run)=>{const score=value.score+250+value.floor*90;const nextFloor=value.floor+1;if(nextFloor>=9){const won={...value,score:score+2000,phase:"won" as const,floor:nextFloor};saveBest(won.score);audio.play("complete");return won}audio.play("success");return{...value,score,floor:nextFloor,phase:(nextFloor===3||nextFloor===6?"relic":"reward") as Phase,enemy:null,hand:[],draw:[],discard:[]}};
  const playCard=(index:number)=>{setRun(old=>{if(old.phase!=="battle")return old;const id=old.hand[index],card=CARDS[id];if(!card||card.cost>old.energy)return old;let next={...old,energy:old.energy-card.cost,hand:old.hand.filter((_,i)=>i!==index),discard:id==="mend"?old.discard:[...old.discard,id]};let damage=0;if(card.type==="attack"||id==="brand"){damage=id==="echo"?card.value*2:id==="gambit"?card.value+old.floor*2:card.value;if(old.relics.includes("Red Seal"))damage+=2;const absorbed=Math.min(next.enemyBlock,damage);next.enemyBlock-=absorbed;next.enemyHp-=damage-absorbed}if(id==="guard"||id==="focus"||id==="ward")next.heroBlock+=card.value+(old.relics.includes("Margin Note")?2:0);if(id==="bleed")next.poison+=card.value;if(id==="brand")next.poison+=3;if(id==="mend")next.hp=Math.min(next.maxHp,next.hp+card.value);if(id==="quill")next=drawCards(next,1);if(id==="focus")next=drawCards(next,2);if(next.enemyHp<=0)return resolveWin(next);audio.play(card.type==="attack"?"good":"tap");return next})};
  const endTurn=()=>{setRun(old=>{if(old.phase!=="battle"||!old.enemy)return old;const enemyHp=old.enemyHp-old.poison,poison=Math.max(0,old.poison-1),discard=[...old.discard,...old.hand];if(enemyHp<=0)return resolveWin({...old,enemyHp,poison,heroBlock:0,discard,hand:[]});let enemyBlock=0,blight=old.blight;let damage=old.enemy.attack+Math.floor(old.floor/2);const heavy=old.turn%4===0,bailiff=old.enemy.id==="bailiff"&&old.turn%2===1;if(old.enemy.id==="scribe"&&old.turn%3===0)damage+=5;if(old.enemy.id==="moth")blight+=2;if(bailiff){enemyBlock=12+old.floor*2;damage=0}if(heavy&&old.enemy.boss)damage+=10;const taken=Math.max(0,damage-old.heroBlock)+blight;blight=Math.max(0,blight-1);let next:Run={...old,enemyHp,enemyBlock,poison,blight,hp:old.hp-taken,heroBlock:0,energy:old.relics.includes("Glass Nib")?4:3,turn:old.turn+1,discard,hand:[]};if(next.hp<=0){next.phase="lost";saveBest(next.score);audio.play("error");return next}next=drawCards(next,5);audio.play(taken?"error":"navigate");return next})};
  const takeReward=(card?:CardId)=>{setRun(old=>({...old,deck:card?[...old.deck,card]:old.deck,phase:"map"}));audio.play("good")};
  const takeRelic=(relic:Relic)=>{setRun(old=>({...old,relics:[...old.relics,relic],hp:Math.min(old.maxHp,old.hp+12),phase:"reward"}));audio.play("complete")};
  const rewardChoices=useMemo(()=>[REWARDS[(run.floor*3)%REWARDS.length],REWARDS[(run.floor*3+3)%REWARDS.length],REWARDS[(run.floor*3+6)%REWARDS.length]],[run.floor]);
  const intent=run.enemy?(run.enemy.id==="bailiff"&&run.turn%2===1?"FORTIFY +12":run.enemy.boss&&run.turn%4===0?`RUINOUS ${run.enemy.attack+10}`:run.enemy.id==="moth"?`STRIKE ${run.enemy.attack} + SPORES`:`STRIKE ${run.enemy.attack+Math.floor(run.floor/2)}`):"";
  const cardView=(id:CardId,index:number,disabled=false)=>{const card=CARDS[id];return <button key={`${id}-${index}`} className={`${styles.card} ${styles[card.type]}`} style={{"--tilt":`${(index%3-1)*1.1}deg`} as CSSProperties} onClick={()=>playCard(index)} disabled={disabled||run.energy<card.cost}><em>{card.cost}</em><strong>{card.name}</strong><p>{card.text}</p><small>{card.type.toUpperCase()}</small></button>};
  const side=<div className={styles.sideRelic}><span>RELICS</span><p>{run.relics.length?run.relics.join(" · "):"No relics claimed."}</p><div className={styles.decklist}>DECK {run.deck.length} · DRAW {run.draw.length} · DISCARD {run.discard.length}</div></div>;
  return <DeepFrame number="016" title="Ash & Ink" collection="DECKBUILDING ROGUELITE" tagline="Write the attack. Survive the edit." accent="#d8b878" accent2="#b43b32" status={run.phase==="battle"?`ACT ${Math.floor(run.floor/3)+1} · TURN ${run.turn}`:run.phase.toUpperCase()} stats={[{label:"LIFE",value:`${run.hp}/${run.maxHp}`},{label:"FLOOR",value:`${Math.min(9,run.floor+1)}/9`},{label:"BEST",value:best}]} sound={audio.enabled} onSound={audio.toggle} onRestart={restart} objective="Build a deck strong enough to survive nine encounters and the Final Editor." instructions={["Cards cost ink. Spend up to three each turn, then face the enemy intent.","Block expires every turn; poison pierces enemy armor, while blight pierces your block.","Choose one new card after each fight and a permanent relic after each act."]} side={side}>
    <div className={`${deep.board} ${styles.tome}`}>
      <div className={styles.paperHead}><span>THE ASH ARCHIVE · ACT {Math.floor(run.floor/3)+1}</span><b>Ash & Ink</b><span>RUN SCORE {run.score}</span></div>
      {run.phase==="ready"&&<section className={styles.start}><div><span className={styles.eyebrow}>A HAND-DRAWN ROGUELITE</span><h2>Every mark<br/>has a cost.</h2><p>Nine encounters. Drafted cards. Visible enemy intentions. Three act relics. One life.</p><button onClick={restart}>OPEN THE TOME</button></div></section>}
      {run.phase==="map"&&<section className={styles.map}><div><span className={styles.eyebrow}>PAGE {run.floor+1} OF 9</span><h2>Choose the next stain.</h2><p>You may read the threat. You may not turn back.</p><div className={styles.paths}>{paths.map(enemy=><button key={enemy.id} onClick={()=>enterBattle(enemy)}><i>{enemy.icon}</i><b>{enemy.name}</b><span>{enemy.note}<br/>Base life {Math.round(enemy.hp*(1+run.floor*.12))}</span></button>)}</div></div></section>}
      {run.phase==="battle"&&run.enemy&&<section className={styles.battle}><div className={styles.enemy}><div className={`${styles.enemyArt} ${run.enemy.boss?styles.boss:""}`}/><h2>{run.enemy.name}</h2><div className={styles.intent}>INTENT · {intent}</div><div className={styles.bar}><i style={{width:`${Math.max(0,run.enemyHp/(run.enemy.hp*(1+run.floor*.12))*100)}%`}}/></div><small>{Math.max(0,Math.ceil(run.enemyHp))} LIFE · {run.enemyBlock} BLOCK · {run.poison} POISON</small></div><div className={styles.hero}><div className={styles.heroTop}><div><span>LIFE</span><b>{run.hp}</b></div><div><span>BLOCK</span><b>{run.heroBlock}</b></div><div><span>INK</span><b>{run.energy}</b></div></div><div className={styles.effects}>Turn {run.turn}. {run.blight?`${run.blight} blight damage will pierce block. `:""}Read the intent, then write your answer.</div><div className={styles.hand}>{run.hand.map((id,index)=>cardView(id,index))}</div><button className={styles.end} onClick={endTurn}>END TURN →</button></div></section>}
      {run.phase==="reward"&&<section className={styles.rewards}><div><span className={styles.eyebrow}>THE PAGE IS YOURS</span><h2>Add one line.</h2><p>Choose a card for the rest of this run.</p><div className={styles.rewardCards}>{rewardChoices.map(id=>{const card=CARDS[id];return <button key={id} className={`${styles.card} ${styles[card.type]}`} onClick={()=>takeReward(id)}><em>{card.cost}</em><strong>{card.name}</strong><p>{card.text}</p><small>{card.type.toUpperCase()}</small></button>})}</div><button className={styles.skip} onClick={()=>takeReward()}>Skip the draft</button></div></section>}
      {run.phase==="relic"&&<section className={styles.rewards}><div><span className={styles.eyebrow}>ACT COMPLETE · CLAIM A RELIC</span><h2>Keep what survived.</h2><div className={styles.relics}><button onClick={()=>takeRelic("Red Seal")}><b>RED SEAL</b><span>Every attack deals +2.</span></button><button onClick={()=>takeRelic("Glass Nib")}><b>GLASS NIB</b><span>Begin every turn with 4 ink.</span></button><button onClick={()=>takeRelic("Margin Note")}><b>MARGIN NOTE</b><span>Every block card gains +2.</span></button></div></div></section>}
      {(run.phase==="won"||run.phase==="lost")&&<section className={styles.start}><div><span className={`${styles.eyebrow} ${styles.red}`}>{run.phase==="won"?"THE FINAL EDIT STANDS":"THE PAGE WENT DARK"}</span><h2>{run.phase==="won"?"You wrote the ending.":"Start a cleaner draft."}</h2><p>Run score {run.score}. Deck size {run.deck.length}. Relics carried {run.relics.length}.</p><button onClick={restart}>NEW MANUSCRIPT</button></div></section>}
    </div>
  </DeepFrame>
}
