"use client";

import Image from "next/image";
import Link from "next/link";
import { useMemo, useState } from "react";
import styles from "./arcade.module.css";
import shelf from "./classics.module.css";
import depth from "./depth.module.css";
import feature from "./features.module.css";

type DeepArt="box"|"salvage"|"lumen"|"twofold"|"ash"|"pinball"|"kingdom";
type Game = { number:string; title:string; short:string; genre:string; tags:string[]; time:string; href:string; image?:string; alt:string; tone:string; release:string; classic?:"drop"|"courier"|"paddle"|"maze"|"coil"; deep?:DeepArt };
const GAMES: Game[] = [
  { number:"018",title:"While You Slept",short:"Grow a persistent pocket kingdom through worker allocation, building, policy, and offline production.",genre:"Persistent kingdom",tags:["STRATEGY","MANAGEMENT"],time:"ONGOING",href:"/games/while-you-slept/",alt:"A small kingdom continuing beneath a golden sky",tone:"gold",release:"NEW",deep:"kingdom" },
  { number:"017",title:"Faultline Pinball",short:"Light seismic stations, build combos, raise the multiplier, and wake quake-powered multiball.",genre:"Physics pinball",tags:["ARCADE","SCORE ATTACK"],time:"3–15 MIN",href:"/games/faultline-pinball/",alt:"Neon original pinball table",tone:"pink",release:"NEW",deep:"pinball" },
  { number:"016",title:"Ash & Ink",short:"Draft a combat deck across nine encounters, visible enemy intents, and three permanent relics.",genre:"Deckbuilding roguelite",tags:["STRATEGY","ROGUELITE"],time:"20–40 MIN",href:"/games/ash-and-ink/",alt:"Hand-drawn cards in an old tome",tone:"paper",release:"NEW",deep:"ash" },
  { number:"015",title:"Twofold Arena",short:"Steal the core in a neon objective arena—solo against AI or with two players on one keyboard.",genre:"Arena objective",tags:["MULTIPLAYER","ARCADE"],time:"3–12 MIN",href:"/games/twofold-arena/",alt:"Cyan and magenta rivals in a split arena",tone:"cyan",release:"NEW",deep:"twofold" },
  { number:"014",title:"Lumenhold",short:"Build four tower classes, manage a light economy, and survive twelve escalating waves.",genre:"Tower defense",tags:["STRATEGY","TACTICAL"],time:"15–30 MIN",href:"/games/lumenhold/",alt:"A glowing tower holding back the night",tone:"gold",release:"NEW",deep:"lumen" },
  { number:"013",title:"Salvage Vector",short:"Fight through five zero-gravity sectors and rebuild your ship from the wreckage between jumps.",genre:"Zero-G roguelite",tags:["ACTION","ROGUELITE"],time:"8–20 MIN",href:"/games/salvage-vector/",alt:"A small ship crossing a debris field",tone:"blue",release:"NEW",deep:"salvage" },
  { number:"012",title:"Black Box Daily",short:"Use six probes to discover the hidden machine rule—the same deterministic puzzle for everyone today.",genre:"Daily logic",tags:["DAILY","PUZZLE"],time:"2–8 MIN",href:"/games/black-box-daily/",alt:"A glowing black box inference machine",tone:"green",release:"DAILY",deep:"box" },
  { number:"011",title:"Coilfield",short:"Grow a neon signal through a wrapping field where every fourth charge creates new hazards.",genre:"Tail survival",tags:["CLASSICS","ARCADE"],time:"2–10 MIN",href:"/games/coilfield/",alt:"Neon signal coil in a grid",tone:"acid",release:"CLASSIC",classic:"coil" },
  { number:"010",title:"Circuit Eater",short:"Consume every charge node in an original security maze before three drones close in.",genre:"Maze chase",tags:["CLASSICS","ARCADE"],time:"3–8 MIN",href:"/games/circuit-eater/",alt:"Electric maze and security drones",tone:"blue",release:"CLASSIC",classic:"maze" },
  { number:"009",title:"Pulse Paddle",short:"Deflect an accelerating energy pulse and beat the station defense system to seven.",genre:"Paddle duel",tags:["CLASSICS","SPORT"],time:"2–6 MIN",href:"/games/pulse-paddle/",alt:"Two neon paddles and an energy pulse",tone:"cyan",release:"CLASSIC",classic:"paddle" },
  { number:"008",title:"Star Courier",short:"Cross the moonlit rooftops, recover nine lost parcels, and reach the launch beacon.",genre:"Platform run",tags:["CLASSICS","ACTION"],time:"4–10 MIN",href:"/games/star-courier/",alt:"Robot courier leaping across lunar rooftops",tone:"moon",release:"CLASSIC",classic:"courier" },
  { number:"007",title:"Sector Drop",short:"Rotate falling cargo formations and keep a damaged orbital launch grid open.",genre:"Falling blocks",tags:["CLASSICS","PUZZLE"],time:"2–15 MIN",href:"/games/sector-drop/",alt:"Colorful cargo blocks falling through space",tone:"space",release:"CLASSIC",classic:"drop" },
  { number:"006",title:"Room 404",short:"Escape an abandoned computer desktop by following the clues its owner left behind.",genre:"Desktop escape",tags:["PUZZLE","EXPLORATION"],time:"10–20 MIN",href:"/games/room-404/",image:"/arcade/room-404-cover.jpg",alt:"Surreal lavender computer room",tone:"violet",release:"NEW" },
  { number:"005",title:"Signal Lost",short:"Tune five impossible radio carriers hidden inside the static and decode the warning.",genre:"Audio mystery",tags:["AUDIO","MYSTERY"],time:"8–14 MIN",href:"/games/signal-lost/",image:"/arcade/signal-lost-cover.jpg",alt:"Abandoned shortwave listening station",tone:"green",release:"NEW" },
  { number:"004",title:"Sixty-Second CEO",short:"Make ten frantic decisions and learn what your leadership is really worth.",genre:"Business panic",tags:["STRATEGY","SCORE ATTACK"],time:"1–5 MIN",href:"/games/sixty-second-ceo/",image:"/arcade/sixty-second-ceo-cover.jpg",alt:"Colorful executive boardroom in chaos",tone:"orange",release:"NEW" },
  { number:"003",title:"Alibi File",short:"Compare testimony and evidence to find the contradiction that breaks each alibi.",genre:"Detective deduction",tags:["DEDUCTION","STORY"],time:"10–18 MIN",href:"/games/alibi-file/",image:"/arcade/alibi-file-cover.jpg",alt:"Detective desk with evidence and red string",tone:"paper",release:"NEW" },
  { number:"002",title:"2:17 AM",short:"Match limited response units to a city full of emergencies before the clock wins.",genre:"Emergency strategy",tags:["STRATEGY","MANAGEMENT"],time:"8–15 MIN",href:"/games/2-17-am/",image:"/arcade/2-17-am-cover.jpg",alt:"Night emergency dispatch center",tone:"red",release:"FEATURED" },
  { number:"001",title:"Break the App",short:"Four ordinary interfaces. Four hidden logic bugs. Find the loophole without using code.",genre:"Interface puzzle",tags:["PUZZLE","LOGIC"],time:"15–25 MIN",href:"/games/break-the-app/",image:"/og.png",alt:"Break the App puzzle game",tone:"lime",release:"ORIGINAL" },
];
const FILTERS=["ALL","DAILY","ROGUELITE","MULTIPLAYER","CLASSICS","ARCADE","PUZZLE","STRATEGY","MYSTERY","AUDIO"];
const DEEP=GAMES.filter(game=>game.deep);
const ORIGINALS=GAMES.filter(game=>!game.classic&&!game.deep);
const CLASSICS=GAMES.filter(game=>game.classic);

function ClassicCover({game}: {game: Game}) { return <div className={`${shelf.classicArt} ${shelf[`classic_${game.classic}`]}`} role="img" aria-label={game.alt}><div className={shelf.pixelSun}/><div className={shelf.pixelGrid}/><i/><i/><i/><b>{game.number}</b></div> }
function DeepCover({game}:{game:Game}){return <div className={`${depth.art} ${depth[game.deep!]}`} role="img" aria-label={game.alt}><div className={depth.grid}/><i/><b>GAME {game.number}</b></div>}
function Cover({game,priority=false}:{game:Game;priority?:boolean}){return game.image?<Image src={game.image} alt={game.alt} fill sizes="(max-width:720px) 100vw, 440px" loading={priority?"eager":"lazy"}/>:game.deep?<DeepCover game={game}/>:<ClassicCover game={game}/>}

export default function ArcadeCatalog(){
  const [filter,setFilter]=useState("ALL");
  const [query,setQuery]=useState("");
  const filtered=useMemo(()=>GAMES.filter(game=>(filter==="ALL"||game.tags.includes(filter))&&`${game.title} ${game.genre} ${game.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase())),[filter,query]);
  const playRandom=()=>{const game=GAMES[Math.floor(Math.random()*GAMES.length)];window.location.assign(game.href)};
  return <main className={styles.arcade}>
    <header className={styles.topbar}><Link href="/" className={styles.brand}><span className={styles.brandMark}><i/><i/><i/></span><div><b>FAIRBYTE</b><span>ARCADE</span></div></Link><nav><a href="#daily">Daily</a><a href="#deep">New worlds</a><a href="#classics">Classics</a><a href="#catalog">All games</a><a href="#project">100 Game Project</a></nav><a className={styles.studioLink} href="https://fairbyte.us/">FAIRBYTE.US ↗</a></header>
    <section className={styles.hero}>
      <Image src="/arcade/2-17-am-cover.jpg" alt="A nighttime emergency dispatch center" fill loading="eager" sizes="100vw" className={styles.heroArt}/><div className={styles.heroShade}/>
      <div className={styles.heroCopy}><span><i/> EDITOR&apos;S SPOTLIGHT · GAME 002</span><h1><em>2:17</em> AM</h1><p>Four response units. Eight minutes. A city that refuses to wait its turn.</p><div className={styles.heroTags}><span>STRATEGY</span><span>8–15 MIN</span><span>TOUCH + MOUSE</span></div><div className={styles.heroActions}><Link href="/games/2-17-am/">▶ PLAY NOW</Link><a href="#catalog">BROWSE CATALOG</a></div></div>
      <aside className={styles.heroPanel}><span>FAIRBYTE ARCADE</span><b>18</b><small>PLAYABLE GAMES</small><div><i style={{width:"18%"}}/></div><p>Eighteen releases on the road to one hundred. Every game runs instantly in your browser.</p></aside>
    </section>
    <section className={styles.valueStrip}><div><b>18</b><span>GAMES LIVE</span></div><div><b>0</b><span>DOWNLOADS</span></div><div><b>0</b><span>ACCOUNTS</span></div><p><strong>Pick a world.</strong> Your progress stays on this device.</p></section>
    <section className={feature.daily} id="daily"><div className={feature.dailyArt}><DeepCover game={DEEP[6]}/></div><div className={feature.dailyCopy}><span>TODAY&apos;S DAILY BYTE · GAME 012</span><h2>One machine.<br/>One hidden rule.</h2><p>Everyone gets the same Black Box every day. Spend six probes, make one final inference, protect your streak, then share the result without spoiling the answer.</p><div><Link href="/games/black-box-daily/">PLAY TODAY&apos;S PUZZLE →</Link><button onClick={playRandom}>SURPRISE ME</button></div></div><aside><b>DAILY</b><span>NEW PUZZLE AT MIDNIGHT UTC</span><i>NO ACCOUNT REQUIRED</i></aside></section>
    <section className={feature.depthShelf} id="deep"><div className={styles.sectionHead}><div><span>THE DEPTH DROP · GAMES 012–018</span><h2>Seven games built to keep.</h2></div><p>Daily deduction, run-building action, tower defense, local multiplayer, a full deckbuilder, original pinball, and a kingdom that keeps working while you are gone.</p></div><div className={feature.depthRail}>{DEEP.map(game=><Link href={game.href} key={game.number} className={feature.depthCard}><div><DeepCover game={game}/><span>{game.release}</span><b>▶</b></div><small>{game.genre.toUpperCase()} · {game.time}</small><h3>{game.title}</h3><p>{game.short}</p><footer>PLAY GAME <b>↗</b></footer></Link>)}</div></section>
    <section className={shelf.classicsShelf} id="classics"><div className={styles.sectionHead}><div><span>THE RE-CODED COLLECTION</span><h2>Classics, rebuilt our way.</h2></div><p>Foundational arcade rules in entirely new worlds—with original code, characters, art, sound, level design, and one fresh twist in every cabinet.</p></div><div className={shelf.cabinetRail}>{CLASSICS.map(game=><Link href={game.href} key={game.number} className={shelf.cabinet}><ClassicCover game={game}/><div><small>GAME {game.number} · {game.genre.toUpperCase()}</small><h3>{game.title}</h3><p>{game.short}</p><span>INSERT NO COIN <b>PLAY →</b></span></div></Link>)}</div></section>
    <section className={styles.newShelf} id="new"><div className={styles.sectionHead}><div><span>FAIRBYTE ORIGINALS</span><h2>The first six worlds.</h2></div><p>Deduction, business strategy, audio mystery, desktop escape, emergency management, and interface puzzles—each with its own visual language.</p></div><div className={styles.posterRail}>{ORIGINALS.slice(0,5).map((game,i)=><Link href={game.href} className={`${styles.poster} ${styles[game.tone]}`} key={game.number}><div><Cover game={game} priority={i<2}/><span>{game.release}</span><b>▶</b></div><small>GAME {game.number} · {game.genre.toUpperCase()}</small><h3>{game.title}</h3><p>{game.short}</p><footer><span>{game.time}</span><strong>PLAY ↗</strong></footer></Link>)}</div></section>
    <section className={styles.catalog} id="catalog"><div className={styles.sectionHead}><div><span>THE COMPLETE LIBRARY</span><h2>Choose your next game.</h2></div><label><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search the catalog" aria-label="Search games"/></label></div><div className={styles.filters}>{FILTERS.map(item=><button key={item} onClick={()=>setFilter(item)} className={filter===item?styles.activeFilter:""}>{item}</button>)}</div><div className={styles.gameGrid}>{filtered.map(game=><Link href={game.href} key={game.number} className={styles.gameTile}><div className={styles.tileArt}><Cover game={game}/><div/><span>#{game.number}</span><b>▶</b></div><div className={styles.tileCopy}><span>{game.tags.join(" · ")}</span><h3>{game.title}</h3><p>{game.short}</p><footer><i>{game.time}</i><b>PLAY GAME ↗</b></footer></div></Link>)}</div>{filtered.length===0&&<div className={styles.empty}><b>NO SIGNAL</b><p>No current release matches that search.</p><button onClick={()=>{setFilter("ALL");setQuery("")}}>RESET CATALOG</button></div>}</section>
    <section className={styles.project} id="project"><div className={styles.projectArt}><span>100</span><i>BROWSER GAMES</i></div><div className={styles.projectCopy}><span>THE 100 GAME PROJECT</span><h2>Release deeply.<br/>Follow what players love.</h2><p>Fairbyte Arcade is a public experiment in building a varied catalog one strong game loop at a time. The games players return to will grow into larger releases.</p><div><span>18 RELEASED</span><span>82 TO GO</span></div><div className={styles.progress}><i style={{width:"18%"}}/></div><small>TARGET · DECEMBER 2026</small></div><aside><span>NEXT ON THE BOARD</span><article><b>019</b><h3>Last Train North</h3><p>Choose who boards the final evacuation train.</p></article><article><b>020</b><h3>Tiny Power Grid</h3><p>Bring a dark city back online without overloading it.</p></article><article><b>021</b><h3>Deep Signal</h3><p>Map a living ocean from a fragile submersible.</p></article></aside></section>
    <footer className={styles.footer}><Link href="/" className={styles.brand}><span className={styles.brandMark}><i/><i/><i/></span><div><b>FAIRBYTE</b><span>ARCADE</span></div></Link><p>ORIGINAL BROWSER GAMES · BUILT IN CHICAGO</p><div><a href="https://fairbyte.us/">STUDIO</a><a href="#catalog">ALL GAMES</a><a href="mailto:hello@fairbyte.us">FEEDBACK</a></div></footer>
  </main>
}
