"use client";

import Image from "next/image";
import Link from "next/link";
import { useMemo, useState } from "react";
import styles from "./arcade.module.css";
import shelf from "./classics.module.css";

type Game = { number:string; title:string; short:string; genre:string; tags:string[]; time:string; href:string; image?:string; alt:string; tone:string; release:string; classic?:"drop"|"courier"|"paddle"|"maze"|"coil" };
const GAMES: Game[] = [
  { number:"011",title:"Coilfield",short:"Grow a neon signal through a wrapping field where every fourth charge creates new hazards.",genre:"Tail survival",tags:["CLASSICS","ARCADE"],time:"2–10 MIN",href:"/games/coilfield/",alt:"Neon signal coil in a grid",tone:"acid",release:"CLASSIC",classic:"coil" },
  { number:"010",title:"Circuit Eater",short:"Consume every charge node in an original security maze before three drones close in.",genre:"Maze chase",tags:["CLASSICS","ARCADE"],time:"3–8 MIN",href:"/games/circuit-eater/",alt:"Electric maze and security drones",tone:"blue",release:"CLASSIC",classic:"maze" },
  { number:"009",title:"Pulse Paddle",short:"Deflect an accelerating energy pulse and beat the station defense system to seven.",genre:"Paddle duel",tags:["CLASSICS","SPORT"],time:"2–6 MIN",href:"/games/pulse-paddle/",alt:"Two neon paddles and an energy pulse",tone:"cyan",release:"CLASSIC",classic:"paddle" },
  { number:"008",title:"Star Courier",short:"Cross the moonlit rooftops, recover nine lost parcels, and reach the launch beacon.",genre:"Platform run",tags:["CLASSICS","ACTION"],time:"4–10 MIN",href:"/games/star-courier/",alt:"Robot courier leaping across lunar rooftops",tone:"moon",release:"CLASSIC",classic:"courier" },
  { number:"007",title:"Sector Drop",short:"Rotate falling cargo formations and keep a damaged orbital launch grid open.",genre:"Falling blocks",tags:["CLASSICS","PUZZLE"],time:"2–15 MIN",href:"/games/sector-drop/",alt:"Colorful cargo blocks falling through space",tone:"space",release:"CLASSIC",classic:"drop" },
  { number:"006",title:"Room 404",short:"Escape an abandoned computer desktop by following the clues its owner left behind.",genre:"Desktop escape",tags:["PUZZLE","EXPLORATION"],time:"10–20 MIN",href:"/games/room-404/",image:"/arcade/room-404-cover.jpg",alt:"Surreal lavender computer room",tone:"violet",release:"NEW" },
  { number:"005",title:"Signal Lost",short:"Tune five impossible radio carriers hidden inside the static and decode the warning.",genre:"Audio mystery",tags:["AUDIO","MYSTERY"],time:"8–14 MIN",href:"/games/signal-lost/",image:"/arcade/signal-lost-cover.jpg",alt:"Abandoned shortwave listening station",tone:"green",release:"NEW" },
  { number:"004",title:"Sixty-Second CEO",short:"Make ten frantic decisions and learn what your leadership is really worth.",genre:"Business panic",tags:["STRATEGY","SCORE ATTACK"],time:"1–5 MIN",href:"/games/sixty-second-ceo/",image:"/arcade/sixty-second-ceo-cover.jpg",alt:"Colorful executive boardroom in chaos",tone:"orange",release:"NEW" },
  { number:"003",title:"Alibi File",short:"Compare testimony and evidence to find the contradiction that breaks each alibi.",genre:"Detective deduction",tags:["DEDUCTION","STORY"],time:"10–18 MIN",href:"/games/alibi-file/",image:"/arcade/alibi-file-cover.jpg",alt:"Detective desk with evidence and red string",tone:"paper",release:"NEW" },
  { number:"002",title:"2:17 AM",short:"Match limited response units to a city full of emergencies before the clock wins.",genre:"Emergency strategy",tags:["STRATEGY","MANAGEMENT"],time:"8–15 MIN",href:"/games/2-17-am/",image:"/arcade/2-17-am-cover.jpg",alt:"Night emergency dispatch center",tone:"red",release:"FEATURED" },
  { number:"001",title:"Break the App",short:"Four ordinary interfaces. Four hidden logic bugs. Find the loophole without using code.",genre:"Interface puzzle",tags:["PUZZLE","LOGIC"],time:"15–25 MIN",href:"/games/break-the-app/",image:"/og.png",alt:"Break the App puzzle game",tone:"lime",release:"ORIGINAL" },
];
const FILTERS=["ALL","CLASSICS","ARCADE","PUZZLE","STRATEGY","MYSTERY","AUDIO"];
const ORIGINALS=GAMES.filter(game=>!game.classic);
const CLASSICS=GAMES.filter(game=>game.classic);

function ClassicCover({game}: {game: Game}) { return <div className={`${shelf.classicArt} ${shelf[`classic_${game.classic}`]}`} role="img" aria-label={game.alt}><div className={shelf.pixelSun}/><div className={shelf.pixelGrid}/><i/><i/><i/><b>{game.number}</b></div> }
function Cover({game,priority=false}:{game:Game;priority?:boolean}){return game.image?<Image src={game.image} alt={game.alt} fill sizes="(max-width:720px) 100vw, 440px" loading={priority?"eager":"lazy"}/>:<ClassicCover game={game}/>}

export default function ArcadeCatalog(){
  const [filter,setFilter]=useState("ALL");
  const [query,setQuery]=useState("");
  const filtered=useMemo(()=>GAMES.filter(game=>(filter==="ALL"||game.tags.includes(filter))&&`${game.title} ${game.genre} ${game.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase())),[filter,query]);
  return <main className={styles.arcade}>
    <header className={styles.topbar}><Link href="/" className={styles.brand}><span className={styles.brandMark}><i/><i/><i/></span><div><b>FAIRBYTE</b><span>ARCADE</span></div></Link><nav><a href="#classics">Classics</a><a href="#new">Originals</a><a href="#catalog">All games</a><a href="#project">100 Game Project</a></nav><a className={styles.studioLink} href="https://fairbyte.us/">FAIRBYTE.US ↗</a></header>
    <section className={styles.hero}>
      <Image src="/arcade/2-17-am-cover.jpg" alt="A nighttime emergency dispatch center" fill loading="eager" sizes="100vw" className={styles.heroArt}/><div className={styles.heroShade}/>
      <div className={styles.heroCopy}><span><i/> EDITOR&apos;S SPOTLIGHT · GAME 002</span><h1><em>2:17</em> AM</h1><p>Four response units. Eight minutes. A city that refuses to wait its turn.</p><div className={styles.heroTags}><span>STRATEGY</span><span>8–15 MIN</span><span>TOUCH + MOUSE</span></div><div className={styles.heroActions}><Link href="/games/2-17-am/">▶ PLAY NOW</Link><a href="#catalog">BROWSE CATALOG</a></div></div>
      <aside className={styles.heroPanel}><span>FAIRBYTE ARCADE</span><b>11</b><small>PLAYABLE GAMES</small><div><i style={{width:"11%"}}/></div><p>Eleven releases on the road to one hundred. Every game runs instantly in your browser.</p></aside>
    </section>
    <section className={styles.valueStrip}><div><b>11</b><span>GAMES LIVE</span></div><div><b>0</b><span>DOWNLOADS</span></div><div><b>0</b><span>ACCOUNTS</span></div><p><strong>Pick a world.</strong> Your progress stays on this device.</p></section>
    <section className={shelf.classicsShelf} id="classics"><div className={styles.sectionHead}><div><span>THE RE-CODED COLLECTION</span><h2>Classics, rebuilt our way.</h2></div><p>Foundational arcade rules in entirely new worlds—with original code, characters, art, sound, level design, and one fresh twist in every cabinet.</p></div><div className={shelf.cabinetRail}>{CLASSICS.map(game=><Link href={game.href} key={game.number} className={shelf.cabinet}><ClassicCover game={game}/><div><small>GAME {game.number} · {game.genre.toUpperCase()}</small><h3>{game.title}</h3><p>{game.short}</p><span>INSERT NO COIN <b>PLAY →</b></span></div></Link>)}</div></section>
    <section className={styles.newShelf} id="new"><div className={styles.sectionHead}><div><span>FAIRBYTE ORIGINALS</span><h2>New worlds, no reskins.</h2></div><p>Deduction, business strategy, audio mystery, desktop escape, emergency management, and interface puzzles—each with its own visual language.</p></div><div className={styles.posterRail}>{ORIGINALS.slice(0,5).map((game,i)=><Link href={game.href} className={`${styles.poster} ${styles[game.tone]}`} key={game.number}><div><Cover game={game} priority={i<2}/><span>{game.release}</span><b>▶</b></div><small>GAME {game.number} · {game.genre.toUpperCase()}</small><h3>{game.title}</h3><p>{game.short}</p><footer><span>{game.time}</span><strong>PLAY ↗</strong></footer></Link>)}</div></section>
    <section className={styles.catalog} id="catalog"><div className={styles.sectionHead}><div><span>THE COMPLETE LIBRARY</span><h2>Choose your next game.</h2></div><label><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search the catalog" aria-label="Search games"/></label></div><div className={styles.filters}>{FILTERS.map(item=><button key={item} onClick={()=>setFilter(item)} className={filter===item?styles.activeFilter:""}>{item}</button>)}</div><div className={styles.gameGrid}>{filtered.map(game=><Link href={game.href} key={game.number} className={styles.gameTile}><div className={styles.tileArt}><Cover game={game}/><div/><span>#{game.number}</span><b>▶</b></div><div className={styles.tileCopy}><span>{game.tags.join(" · ")}</span><h3>{game.title}</h3><p>{game.short}</p><footer><i>{game.time}</i><b>PLAY GAME ↗</b></footer></div></Link>)}</div>{filtered.length===0&&<div className={styles.empty}><b>NO SIGNAL</b><p>No current release matches that search.</p><button onClick={()=>{setFilter("ALL");setQuery("")}}>RESET CATALOG</button></div>}</section>
    <section className={styles.project} id="project"><div className={styles.projectArt}><span>100</span><i>BROWSER GAMES</i></div><div className={styles.projectCopy}><span>THE 100 GAME PROJECT</span><h2>Release quickly.<br/>Follow what players love.</h2><p>Fairbyte Arcade is a public experiment in building a deep catalog one strong game loop at a time. The games players return to will grow into larger releases.</p><div><span>11 RELEASED</span><span>89 TO GO</span></div><div className={styles.progress}><i style={{width:"11%"}}/></div><small>TARGET · DECEMBER 2026</small></div><aside><span>NEXT ON THE BOARD</span><article><b>012</b><h3>Black Box</h3><p>Learn the hidden rules of an unknown machine.</p></article><article><b>013</b><h3>Last Train North</h3><p>Choose who boards the final evacuation train.</p></article><article><b>014</b><h3>Tiny Power Grid</h3><p>Bring a dark city back online without overloading it.</p></article></aside></section>
    <footer className={styles.footer}><Link href="/" className={styles.brand}><span className={styles.brandMark}><i/><i/><i/></span><div><b>FAIRBYTE</b><span>ARCADE</span></div></Link><p>ORIGINAL BROWSER GAMES · BUILT IN CHICAGO</p><div><a href="https://fairbyte.us/">STUDIO</a><a href="#catalog">ALL GAMES</a><a href="mailto:hello@fairbyte.us">FEEDBACK</a></div></footer>
  </main>
}
