"use client";

import {useCallback,useEffect,useRef,useState} from "react";
import DeepFrame from "../shared/DeepFrame";
import deep from "../shared/deep.module.css";
import {useGameAudio} from "../../useGameAudio";
import styles from "./game.module.css";

type Ball={x:number;y:number;vx:number;vy:number;r:number;live:boolean;trail:{x:number;y:number}[]};
type Bumper={x:number;y:number;r:number;color:string;value:number};
type World={phase:"ready"|"playing"|"over";balls:Ball[];reserve:number;score:number;multiplier:number;quake:number;stations:boolean[];combo:number;comboClock:number;flash:number;shake:number;best:number};
const W=720,H=760;
const BUMPERS:Bumper[]=[{x:250,y:245,r:36,color:"#fd75cf",value:250},{x:455,y:225,r:34,color:"#7ffcff",value:250},{x:350,y:345,r:42,color:"#ffdc65",value:400},{x:185,y:405,r:27,color:"#8e77ff",value:180},{x:520,y:405,r:27,color:"#ff6b72",value:180}];
const STATIONS=[{x:155,y:165},{x:355,y:125},{x:555,y:165}];
const fresh=():World=>({phase:"ready",balls:[],reserve:3,score:0,multiplier:1,quake:0,stations:[false,false,false],combo:0,comboClock:0,flash:0,shake:0,best:0});
const ball=():Ball=>({x:646,y:650,vx:0,vy:-13,r:9,live:true,trail:[]});
const clamp=(value:number,min:number,max:number)=>Math.max(min,Math.min(max,value));
function segmentHit(b:Ball,x1:number,y1:number,x2:number,y2:number,power:number){const dx=x2-x1,dy=y2-y1,len2=dx*dx+dy*dy,t=clamp(((b.x-x1)*dx+(b.y-y1)*dy)/len2,0,1),px=x1+t*dx,py=y1+t*dy,nx=b.x-px,ny=b.y-py,d=Math.hypot(nx,ny);if(d<b.r+8&&b.vy>-.8){const ux=nx/(d||1),uy=ny/(d||1),dot=b.vx*ux+b.vy*uy;b.vx-=2*dot*ux;b.vy-=2*dot*uy;b.vx+=ux*power;b.vy+=uy*power;b.x=px+ux*(b.r+9);b.y=py+uy*(b.r+9);return true}return false}

export default function FaultlinePinball(){
  const audio=useGameAudio();const canvas=useRef<HTMLCanvasElement>(null);const world=useRef<World>(fresh());const keys=useRef({left:false,right:false});const [phase,setPhase]=useState<"ready"|"playing"|"over">("ready");const [score,setScore]=useState(0);const [balls,setBalls]=useState(3);const [activeBalls,setActiveBalls]=useState(0);const [multiplier,setMultiplier]=useState(1);const [quake,setQuake]=useState(0);const [stations,setStations]=useState([false,false,false]);const [best,setBest]=useState(0);
  useEffect(()=>{try{setBest(Number(localStorage.getItem("fairbyte:faultline:best")||0))}catch{}},[]);
  const sync=useCallback(()=>{const w=world.current;setScore(w.score);setBalls(w.reserve);setActiveBalls(w.balls.length);setMultiplier(w.multiplier);setQuake(w.quake);setStations([...w.stations])},[]);
  const restart=useCallback(()=>{const w=fresh();w.phase="playing";w.reserve=2;w.balls=[ball()];world.current=w;setPhase("playing");sync();audio.play("success")},[audio,sync]);
  const setFlipper=useCallback((side:"left"|"right",down:boolean)=>{keys.current[side]=down},[]);
  useEffect(()=>{const down=(event:KeyboardEvent)=>{if(["ArrowLeft","ArrowRight","a","d"," "].includes(event.key))event.preventDefault();if(event.key==="ArrowLeft"||event.key.toLowerCase()==="a")setFlipper("left",true);if(event.key==="ArrowRight"||event.key.toLowerCase()==="d")setFlipper("right",true);if((event.key===" "||event.key==="Enter")&&world.current.phase!=="playing")restart()};const up=(event:KeyboardEvent)=>{if(event.key==="ArrowLeft"||event.key.toLowerCase()==="a")setFlipper("left",false);if(event.key==="ArrowRight"||event.key.toLowerCase()==="d")setFlipper("right",false)};window.addEventListener("keydown",down);window.addEventListener("keyup",up);return()=>{window.removeEventListener("keydown",down);window.removeEventListener("keyup",up)}},[restart,setFlipper]);
  useEffect(()=>{let frame=0,last=performance.now();const ctx=canvas.current?.getContext("2d");if(!ctx)return;const award=(value:number)=>{const w=world.current;w.combo++;w.comboClock=95;w.score+=value*w.multiplier*(1+Math.floor(w.combo/5));w.quake=Math.min(100,w.quake+value/70);w.flash=7;if(w.quake>=100&&w.balls.length===1){w.quake=0;w.balls.push({...ball(),x:360,y:300,vx:-5,vy:-8},{...ball(),x:390,y:315,vx:5,vy:-7});w.multiplier=Math.min(8,w.multiplier+1);w.shake=45;audio.play("complete")}sync()};
    const loop=(now:number)=>{const dt=Math.min(1.55,(now-last)/16.67);last=now;const w=world.current;if(w.phase==="playing"){w.comboClock-=dt;if(w.comboClock<=0)w.combo=0;w.flash=Math.max(0,w.flash-dt);w.shake=Math.max(0,w.shake-dt);const leftAngle=keys.current.left?-.52:.25,rightAngle=keys.current.right?Math.PI+.52:Math.PI-.25;const left={x1:245,y1:650,x2:245+Math.cos(leftAngle)*112,y2:650+Math.sin(leftAngle)*112};const right={x1:475,y1:650,x2:475+Math.cos(rightAngle)*112,y2:650+Math.sin(rightAngle)*112};for(const b of w.balls){if(!b.live)continue;b.vy+=.22*dt;b.x+=b.vx*dt;b.y+=b.vy*dt;b.vx*=.999;b.vy*=.999;b.trail.unshift({x:b.x,y:b.y});b.trail=b.trail.slice(0,9);if(b.x-b.r<47){b.x=47+b.r;b.vx=Math.abs(b.vx)*.88}if(b.x+b.r>674){b.x=674-b.r;b.vx=-Math.abs(b.vx)*.88}if(b.y-b.r<55){b.y=55+b.r;b.vy=Math.abs(b.vy)*.9}if(b.x>605&&b.y>525){b.vx=Math.min(b.vx,-1.4)}
        for(const bumper of BUMPERS){const dx=b.x-bumper.x,dy=b.y-bumper.y,d=Math.hypot(dx,dy);if(d<b.r+bumper.r){const nx=dx/(d||1),ny=dy/(d||1),dot=b.vx*nx+b.vy*ny;b.vx-=2*dot*nx;b.vy-=2*dot*ny;b.vx+=nx*4.5;b.vy+=ny*4.5;b.x=bumper.x+nx*(bumper.r+b.r+1);b.y=bumper.y+ny*(bumper.r+b.r+1);award(bumper.value);audio.play("tap")}}
        STATIONS.forEach((station,index)=>{if(!w.stations[index]&&Math.hypot(b.x-station.x,b.y-station.y)<25){w.stations[index]=true;award(600);audio.play("good");if(w.stations.every(Boolean)){w.stations=[false,false,false];w.multiplier=Math.min(8,w.multiplier+1);w.score+=2500*w.multiplier;w.shake=35;audio.play("success")}}});if(segmentHit(b,left.x1,left.y1,left.x2,left.y2,keys.current.left?8:2)||segmentHit(b,right.x1,right.y1,right.x2,right.y2,keys.current.right?8:2))audio.play("navigate");segmentHit(b,75,520,220,585,1);segmentHit(b,645,520,500,585,1);if(b.y>H+30)b.live=false}
      w.balls=w.balls.filter(b=>b.live);if(!w.balls.length){if(w.reserve>0){w.reserve--;w.balls=[ball()];w.multiplier=1;w.combo=0;sync();audio.play("error")}else{w.phase="over";setPhase("over");setBest(old=>{const next=Math.max(old,w.score);try{localStorage.setItem("fairbyte:faultline:best",String(next))}catch{}return next});audio.play("complete")}}}
      const shake=w.shake>0?(Math.random()-.5)*7:0;ctx.save();ctx.translate(shake,shake);ctx.fillStyle="#09060d";ctx.fillRect(-10,-10,W+20,H+20);const grad=ctx.createLinearGradient(0,0,0,H);grad.addColorStop(0,"#2a0e2d");grad.addColorStop(.55,"#101129");grad.addColorStop(1,"#120713");ctx.fillStyle=grad;ctx.fillRect(30,30,W-60,H-35);ctx.strokeStyle="#fd75cf";ctx.lineWidth=5;ctx.strokeRect(30,30,W-60,H-35);ctx.strokeStyle="#7ffcff33";ctx.lineWidth=1;for(let y=75;y<700;y+=40){ctx.beginPath();ctx.moveTo(45,y);ctx.lineTo(665,y-15);ctx.stroke()}ctx.fillStyle="#130b1d";ctx.strokeStyle="#7ffcff";ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(42,520);ctx.lineTo(220,596);ctx.lineTo(275,710);ctx.lineTo(445,710);ctx.lineTo(500,596);ctx.lineTo(678,520);ctx.stroke();
      ctx.font="900 15px Arial";ctx.textAlign="center";STATIONS.forEach((station,index)=>{ctx.fillStyle=w.stations[index]?"#7ffcff":"#24152d";ctx.shadowColor="#7ffcff";ctx.shadowBlur=w.stations[index]?18:0;ctx.fillRect(station.x-20,station.y-13,40,26);ctx.fillStyle=w.stations[index]?"#071016":"#866e8d";ctx.fillText(String(index+1),station.x,station.y+5)});ctx.shadowBlur=0;BUMPERS.forEach(bumper=>{ctx.fillStyle=bumper.color;ctx.shadowColor=bumper.color;ctx.shadowBlur=24;ctx.beginPath();ctx.arc(bumper.x,bumper.y,bumper.r,0,Math.PI*2);ctx.fill();ctx.fillStyle="#160b1b";ctx.beginPath();ctx.arc(bumper.x,bumper.y,bumper.r*.64,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0});
      const leftAngle=keys.current.left?-.52:.25,rightAngle=keys.current.right?Math.PI+.52:Math.PI-.25;const drawFlip=(x:number,y:number,a:number,color:string)=>{ctx.strokeStyle=color;ctx.shadowColor=color;ctx.shadowBlur=15;ctx.lineWidth=18;ctx.lineCap="round";ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+Math.cos(a)*112,y+Math.sin(a)*112);ctx.stroke();ctx.shadowBlur=0};drawFlip(245,650,leftAngle,"#7ffcff");drawFlip(475,650,rightAngle,"#fd75cf");w.balls.forEach(b=>{b.trail.forEach((point,index)=>{ctx.globalAlpha=(9-index)/35;ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(point.x,point.y,b.r-index*.55,0,Math.PI*2);ctx.fill()});ctx.globalAlpha=1;ctx.fillStyle="#fff";ctx.shadowColor="#fff";ctx.shadowBlur=18;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0});if(w.flash>0){ctx.globalAlpha=w.flash/18;ctx.fillStyle="#fff";ctx.fillRect(30,30,W-60,H-35);ctx.globalAlpha=1}ctx.restore();frame=requestAnimationFrame(loop)};frame=requestAnimationFrame(loop);return()=>cancelAnimationFrame(frame)},[audio,sync]);
  const touch=<div className={styles.touch}><button aria-label="Left flipper" onPointerDown={()=>setFlipper("left",true)} onPointerUp={()=>setFlipper("left",false)} onPointerLeave={()=>setFlipper("left",false)}>LEFT FLIPPER</button><button aria-label="Right flipper" onPointerDown={()=>setFlipper("right",true)} onPointerUp={()=>setFlipper("right",false)} onPointerLeave={()=>setFlipper("right",false)}>RIGHT FLIPPER</button></div>;
  const side=<div className={styles.mission}><span>SEISMIC SURVEY</span><b>LIGHT ALL 3 STATIONS</b><div className={styles.lights}>{stations.map((on,index)=><i key={index} className={on?styles.on:""}/>)}</div><div className={styles.quake}><i style={{width:`${quake}%`}}/></div><span>QUAKE {Math.floor(quake)}% · FULL = MULTIBALL</span></div>;
  return <DeepFrame number="017" title="Faultline Pinball" collection="NEON PHYSICS TABLE" tagline="Light the stations. Wake the fault." accent="#fd75cf" accent2="#7ffcff" status={phase==="playing"?`${activeBalls>1?"MULTIBALL":"BALL IN PLAY"} · ${multiplier}X`:phase.toUpperCase()} stats={[{label:"SCORE",value:score},{label:"BALLS",value:balls},{label:"BEST",value:best}]} sound={audio.enabled} onSound={audio.toggle} onRestart={restart} objective="Keep the ball alive, complete station missions, and trigger quake multiball." instructions={["Left/A and Right/D operate the flippers. Mobile buttons work with either thumb.","Hit bumpers quickly to build a combo; light all three stations for a multiplier.","Fill the quake meter to launch two extra balls. Multipliers reach 8×."]} controls={touch} side={side}>
    <div className={`${deep.board} ${styles.cabinet}`}><canvas ref={canvas} width={W} height={H} className={deep.canvas} aria-label="Faultline neon pinball table"/><div className={styles.screen}><span>SCORE {score.toLocaleString()}</span><span>{multiplier}X · QUAKE {Math.floor(quake)}%</span></div><div className={styles.plunger}>AUTO-LAUNCH CHUTE</div>{phase!=="playing"&&<div className={deep.overlay}><div><span className={styles.pink}>{phase==="over"?"TABLE SILENT":"GAME 017 · ORIGINAL TABLE"}</span><h2>{phase==="over"?score.toLocaleString():"Wake the fault."}</h2><p>Real-time flipper physics, reactive bumpers, combo scoring, survey missions, eight multiplier levels, and quake-powered multiball.</p><button onClick={restart}>{phase==="ready"?"LAUNCH BALL":"PLAY AGAIN"}</button></div></div>}</div>
  </DeepFrame>
}
