"use client";

import {useCallback,useEffect,useRef,useState} from "react";
import ClassicFrame from "../classics/ClassicFrame";
import classic from "../classics/classic.module.css";
import {useGameAudio} from "../../useGameAudio";

type Point={x:number;y:number};type Dir=Point;type Phase="ready"|"playing"|"won"|"over";
const TILE=32;
const MAP=[
  "#####################","#.........#.........#","#.###.###.#.###.###.#","#o###.###.#.###.###o#","#...................#","#.###.#.#####.#.###.#","#.....#...#...#.....#","#####.###...###.#####","#...#.#.......#.#...#","###.#.#.##.##.#.#.###","#.......#...#.......#","#.###.#.#####.#.###.#","#o..#.#...#...#.#..o#","###.#.###.#.###.#.###","#.........#.........#","#.#######...#######.#","#####################"
];
const DIRS:Dir[]=[{x:1,y:0},{x:-1,y:0},{x:0,y:1},{x:0,y:-1}];const key=(p:Point)=>`${p.x},${p.y}`;const open=(p:Point)=>MAP[p.y]?.[p.x]!=="#"&&MAP[p.y]?.[p.x]!==undefined;
const TOTAL=MAP.reduce((sum,row)=>sum+[...row].filter(cell=>cell==="."||cell==="o").length,0);
type World={player:Point;dir:Dir;next:Dir;drones:Point[];dots:Set<string>;surges:Set<string>;surge:number;tick:number};
const fresh=():World=>{const dots=new Set<string>(),surges=new Set<string>();MAP.forEach((row,y)=>[...row].forEach((cell,x)=>{if(cell===".")dots.add(key({x,y}));if(cell==="o")surges.add(key({x,y}))}));return{player:{x:10,y:15},dir:{x:0,y:0},next:{x:-1,y:0},drones:[{x:9,y:8},{x:11,y:8},{x:10,y:10}],dots,surges,surge:0,tick:0}};

export default function CircuitEater(){
  const audio=useGameAudio();const canvas=useRef<HTMLCanvasElement>(null);const world=useRef<World>(fresh());const phaseRef=useRef<Phase>("ready");const [phase,setPhase]=useState<Phase>("ready");const [score,setScore]=useState(0);const scoreRef=useRef(0);const [best,setBest]=useState(0);const [hearts,setHearts]=useState(3);const heartsRef=useRef(3);const [remaining,setRemaining]=useState(TOTAL);
  const setGamePhase=(p:Phase)=>{phaseRef.current=p;setPhase(p)};useEffect(()=>{const timer=window.setTimeout(()=>{try{setBest(Number(localStorage.getItem("fairbyte:circuit-eater:best")||0))}catch{}},0);return()=>window.clearTimeout(timer)},[]);
  const restart=useCallback(()=>{audio.play("navigate");world.current=fresh();scoreRef.current=0;heartsRef.current=3;setScore(0);setHearts(3);setRemaining(world.current.dots.size+world.current.surges.size);setGamePhase("playing")},[audio]);
  const steer=useCallback((dir:Dir)=>{world.current.next=dir;if(phaseRef.current==="ready")restart()},[restart]);
  useEffect(()=>{const onKey=(e:KeyboardEvent)=>{const map:Record<string,Dir>={ArrowLeft:{x:-1,y:0},a:{x:-1,y:0},ArrowRight:{x:1,y:0},d:{x:1,y:0},ArrowUp:{x:0,y:-1},w:{x:0,y:-1},ArrowDown:{x:0,y:1},s:{x:0,y:1}};const d=map[e.key]||map[e.key.toLowerCase()];if(d){e.preventDefault();steer(d)}if((e.key==="Enter"||e.key===" ")&&phaseRef.current!=="playing")restart()};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[restart,steer]);
  useEffect(()=>{const step=()=>{if(phaseRef.current!=="playing")return;const w=world.current;w.tick++;const candidate={x:w.player.x+w.next.x,y:w.player.y+w.next.y};if(open(candidate))w.dir=w.next;const moved={x:w.player.x+w.dir.x,y:w.player.y+w.dir.y};if(open(moved))w.player=moved;const k=key(w.player);if(w.dots.delete(k)){scoreRef.current+=10;setScore(scoreRef.current);audio.play("tap")}if(w.surges.delete(k)){w.surge=55;scoreRef.current+=50;setScore(scoreRef.current);audio.play("success")}if(w.surge>0)w.surge--;if(w.tick%2===0)w.drones=w.drones.map((drone,index)=>{const choices=DIRS.map(d=>({x:drone.x+d.x,y:drone.y+d.y})).filter(open);choices.sort((a,b)=>{const da=Math.abs(a.x-w.player.x)+Math.abs(a.y-w.player.y);const db=Math.abs(b.x-w.player.x)+Math.abs(b.y-w.player.y);return w.surge>0?db-da:da-db});return Math.random()<.74?choices[0]:(choices[(w.tick+index)%choices.length]||drone)});const collision=w.drones.findIndex(d=>d.x===w.player.x&&d.y===w.player.y);if(collision>=0){if(w.surge>0){w.drones[collision]={x:10+collision-1,y:8};scoreRef.current+=200;setScore(scoreRef.current);audio.play("complete")}else{heartsRef.current--;setHearts(heartsRef.current);audio.play("error");w.player={x:10,y:15};w.dir={x:0,y:0};w.drones=[{x:9,y:8},{x:11,y:8},{x:10,y:10}];if(heartsRef.current<=0){setGamePhase("over");setBest(old=>{const value=Math.max(old,scoreRef.current);try{localStorage.setItem("fairbyte:circuit-eater:best",String(value))}catch{}return value})}}}const left=w.dots.size+w.surges.size;setRemaining(left);if(left===0){scoreRef.current+=heartsRef.current*500;setScore(scoreRef.current);audio.play("complete");setGamePhase("won");setBest(old=>{const value=Math.max(old,scoreRef.current);try{localStorage.setItem("fairbyte:circuit-eater:best",String(value))}catch{}return value})}};const id=window.setInterval(step,125);return()=>window.clearInterval(id)},[audio]);
  useEffect(()=>{let id=0;const ctx=canvas.current?.getContext("2d");if(!ctx)return;const draw=()=>{const w=world.current;ctx.fillStyle="#030710";ctx.fillRect(0,0,MAP[0].length*TILE,MAP.length*TILE);MAP.forEach((row,y)=>[...row].forEach((cell,x)=>{if(cell==="#"){ctx.fillStyle="#102d4d";ctx.fillRect(x*TILE+2,y*TILE+2,TILE-4,TILE-4);ctx.strokeStyle="#2d83ba";ctx.strokeRect(x*TILE+6,y*TILE+6,TILE-12,TILE-12)}}));w.dots.forEach(k=>{const [x,y]=k.split(",").map(Number);ctx.fillStyle="#80dfff";ctx.fillRect(x*TILE+14,y*TILE+14,4,4)});w.surges.forEach(k=>{const [x,y]=k.split(",").map(Number);ctx.strokeStyle="#f4ff67";ctx.lineWidth=2;ctx.beginPath();ctx.arc(x*TILE+16,y*TILE+16,8+Math.sin(Date.now()/120)*2,0,Math.PI*2);ctx.stroke()});ctx.save();ctx.translate(w.player.x*TILE+16,w.player.y*TILE+16);ctx.rotate(Math.atan2(w.dir.y||w.next.y,w.dir.x||w.next.x)+Math.PI/4);ctx.fillStyle=w.surge>0?"#f4ff67":"#63e7ff";ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=18;ctx.fillRect(-9,-9,18,18);ctx.restore();w.drones.forEach((d,i)=>{ctx.save();ctx.translate(d.x*TILE+16,d.y*TILE+16);ctx.fillStyle=w.surge>0?"#587084":["#ff4f70","#ff963d","#ba74ff"][i];ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=12;ctx.beginPath();ctx.moveTo(0,-11);ctx.lineTo(11,10);ctx.lineTo(0,6);ctx.lineTo(-11,10);ctx.closePath();ctx.fill();ctx.restore()});id=requestAnimationFrame(draw)};id=requestAnimationFrame(draw);return()=>cancelAnimationFrame(id)},[]);
  const controls=<><button onClick={()=>steer({x:-1,y:0})} aria-label="Move left">←</button><button onClick={()=>steer({x:0,y:-1})} aria-label="Move up">↑</button><button onClick={()=>steer({x:0,y:1})} aria-label="Move down">↓</button><button onClick={()=>steer({x:1,y:0})} aria-label="Move right">→</button></>;
  return <ClassicFrame number="010" title="Circuit Eater" subtitle="A hungry maintenance spark is loose inside a hostile motherboard." accent="#63e7ff" score={score} best={best} status={`${remaining} nodes · ${"◆".repeat(hearts)}${"◇".repeat(3-hearts)}`} sound={audio.enabled} onSound={audio.toggle} onRestart={restart} objective="Consume every charge node while avoiding the three security drones." instructions={["Move with arrows or W/A/S/D.","Bright surge rings let you disable drones briefly.","Clear the entire original maze before losing three sparks."]} controls={controls}>
    <div className={classic.boardWrap}><canvas ref={canvas} width={MAP[0].length*TILE} height={MAP.length*TILE} className={classic.canvas} aria-label="Circuit Eater maze"/><span className={classic.hint}>CHARGE NODES · {remaining}</span>{phase!=="playing"&&<div className={classic.overlay}><div><span>{phase==="won"?"CIRCUIT CLEAN":phase==="over"?"SPARK EXTINGUISHED":"MAINTENANCE CHANNEL 10"}</span><h2>{phase==="won"?"Every node eaten.":phase==="over"?"Drones win.":"Eat the grid."}</h2><p>Collect every blue charge. Surge rings turn the hunters into prey.</p><button onClick={restart}>{phase==="ready"?"ENTER CIRCUIT":"RUN AGAIN"}</button></div></div>}</div>
  </ClassicFrame>;
}
